### ISSUE TITLE
Error in metrip.py -> rmse() when using NN models

### ISSUE THREAD

**Issue by Bartcardi** [mljar/mljar-supervised#104]
When I use NN as model on my dataset I sometimes get np.nan or np.inf during prediction (maybe exploding gradients?) which results in an error during calculation of (r)mse. 

<details><summary>Off topic</summary>
Btw, I love your tool. I am using it regularly for rapid prototyping of new ideas. If you like me to contribute on any level I might be able to help you. E.g., I have implemented GroupKFold which is necessary for my data. This requires some extra input from the user about the groups in the dataset and might break your idea of simple ML for humans. </details>

**Comment by pplonski** [comment]
@Bartcardi thank you for reporting this! Can you tell me what version of the package are you using? If I remember correctly I've fixed a similar problem (missing scaling of the target) and pushed new code to the repo (might be not in PyPi yet).

Thank you very much for kind words :) I need to ask @aplonska to create a contributing guideline.  If you have ideas for new features, please feel free to create the GitHub issue with description. What is more, I will try to create a set of `Good first issue` at the end of this month.

**Comment by Bartcardi** [comment]
I am on commit [94e7f10](https://github.com/mljar/mljar-supervised/commit/94e7f10321a202673449c468da477db817332aa2) of master branch. I use your code directly since I need GroupKFold for my project. 

Great I will wait for you to finish your first issue examples so I can follow your code and documentation style.

**Comment by pplonski** [comment]
Please try `0.4.1` version it should be fixed now. I will work on NN implementation (somewhere in the next 2 weeks range) to make it faster (#108) -  NN should be faster in next minor release :)

**Comment by pplonski** [comment]
It should be fixed.
