### ISSUE TITLE
AutoML.fit returns supervised.exceptions ERROR for binary classification 

### ISSUE THREAD

**Issue by LuisaWz** [mljar/mljar-supervised#105]
I encountered an error when using automl.fit for binary classification: 

supervised.exceptions ERROR The algorithm Baseline is not allowed to use for ML task: binary_classification. Allowed algorithms: ['LightGBM', 'Extra Trees', 'CatBoost', 'Linear']

I'm using:
- Version 0.3.5 of mljar-supervised (installed via pypi)
- Python 3.7.6

Think that there might be another problem, but the bug might get caught by this error message.

**Comment by pplonski** [comment]
Please try `0.4.1` version - it should work now.

**Comment by pplonski** [comment]
I'm closing the issue as I cant it reproduce with the newest version. Thank you for reporting.
