### ISSUE TITLE
Failed call to cuInit: UNKNOWN ERROR (303)

### ISSUE THREAD

**Issue by wulftone** [mljar/mljar-supervised#107]
I tried the latest from `master` and ran into this error:

```
E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)
```

Probably from the Neural Network?

**Comment by pplonski** [comment]
Thank you @wulftone for reporting! I've never seen such an error. What version of TensorFlow do you have installed? Is it CPU or GPU one?

Could you paste some code snippet, so I can try to reproduce the error? Ideally with a data sample.

Are you able to run the package with other algorithms?

**Comment by pplonski** [comment]
Closing, I can't reproduce the issue.
