### ISSUE TITLE
Advanced Encodings for Categoricals

### ISSUE THREAD

**Issue by eladmw** [mljar/mljar-supervised#116]
Add Ability to Category Encode : include encoding with KFold too.

**Comment by pplonski** [comment]
I need more info.

**Comment by eladmw** [comment]
Using ce_encoders library to encode features to certain classes. You can use kfold to help fit and then generate features for your test set.

**Comment by pplonski** [comment]
In https://github.com/mljar/mljar-supervised/issues/250 the Leave-One-Out encoder was added.
