### ISSUE TITLE
Add Incremental Learning 

### ISSUE THREAD

**Issue by eladmw** [mljar/mljar-supervised#118]
Add Incremental Learning : Sklearn has it somewhat implemented, Catboost has sum models, Catboost also has baseline reupdating, Lightgbm has lgb.train, & XGBoost has the "update" setting.

**Comment by pplonski** [comment]
Right now, CatBoost, Xgboost, LightGBM are trained till early stopping or maximum iters reached (10,000) so there is no need to do incremental learning on them. Learning those algorithms without callbacks (to check time constraints) makes them up to 20x (yes, 20x!) faster, so I decided to always train them fully.

However, there is a need to do incremental learning on the AutoML. For example:

1. AutoML is run with 10 models. 
2. The user inspect the models and want to add more models to AutoML to check what will be the performance of the ensemble
3. The user runs automl with new models, during ensemble and stacking all (old and new) models are used.

@eladmw do you think such a feature will be needed?

**Comment by eladmw** [comment]
Honestly, I don't think too many novices will need this, but those in competitions might.

**Comment by eladmw** [comment]
I understand that doing this would probably take considerable effort for functionality that isn't needed too much, so i understand it not being your first priority.

**Comment by pplonski** [comment]
I've implemented the 'restore training' feature in #135.
