### ISSUE TITLE
Genetic Learning Additions

### ISSUE THREAD

**Issue by eladmw** [mljar/mljar-supervised#119]
GPlearn, TPOT (but don't do TPOT, nobody likes it)

**Comment by pplonski** [comment]
Hi @eladmw, can you give more information about this issue? Where you would like to add Genetic Learning? It can be added new tuner, which controls the process of learning and it can be based on genetic programming. Some time ago I wrote a package for feature generation with GA https://github.com/pplonski/gafe. Looking for more info from you!

**Comment by eladmw** [comment]
I think GPlearn is a ScikitLearn compatible genetic learning model. It perform classification, regression, and feature creation. You could add it as a model to your selection of automl models.

**Comment by pplonski** [comment]
I will close it for now. There is a `Tuner` that controls the training. The Genetic Approach might be good, but to get good models it will require a lot of training time.

**Comment by eladmw** [comment]
The model can train much faster if you set a higher error threshold. By doing this, you also help prevent over fitting. You can also limit the types of mathematical operations or depth, or increase njobs.

**Comment by pplonski** [comment]
Do you mean using GP to train the ML model? Do you have an example of such implementation?

I've closed the issue because I don't think I will use GL to control the training in AutoML, like in [TPOT](https://github.com/EpistasisLab/tpot).
