### ISSUE TITLE
Missing Tree visualizations section in 2_DecisionTree README.md

### ISSUE THREAD

**Issue by kfern** [mljar/mljar-supervised#121]
Hi!

I can't find the Tree visualization section In 2_DecisionTree README.md. 

supervised.__version__
'0.5.2'

![image](https://user-images.githubusercontent.com/1898891/87252081-b5945580-c470-11ea-986b-a0710dd54882.png)

Any idea?

**Comment by pplonski** [comment]
Can you send more details, with code example to reproduce? How was `AutoML` class initialized? Do you set `explain_level`? Do you set `mode`?

**Comment by kfern** [comment]
@pplonski Sure :-)

Fresh install on Ubuntu 16.04. The example code is https://github.com/mljar/mljar-examples/blob/master/Iris_classification/Iris_classification.ipynb without changes

The file Iris_classification/AutoML_1/2_DecisionTree/learner_1_tree.svg doesn't exist.

learner_1_tree file content (without extension) is 

![image](https://user-images.githubusercontent.com/1898891/87254429-e5e4ef80-c482-11ea-9ae9-3a902bee5a7c.png)

I'll try another example

**Comment by pplonski** [comment]
Hmmm, looks like missing `graphviz` package (which should be installed with `dtreeviz`). Could you try to install `graphiviz`:

```
pip install -U graphviz
```

**Comment by kfern** [comment]
`python -m pip install -U graphviz`

Defaulting to user installation because normal site-packages is not writeable
Requirement already up-to-date: graphviz in /home/kfern/.local/lib/python3.6/site-packages (0.14)

**Comment by pplonski** [comment]
I added a test for this, and was able to reproduce it on travis build https://travis-ci.org/github/mljar/mljar-supervised/builds/707551742 Looking for fix.

**Comment by pplonski** [comment]
I was able to fix it after installing `graphviz` with apt-get in ubuntu. The `dot` application is needed. To fix it, please run:

```
sudo apt-get install graphviz
```

to check if the `dot` is installed:

```
dot -V
```
(it is capital `V`).

Instructions from `dreeviz` https://github.com/parrt/dtreeviz#verify-graphviz-installation

Please let me know if it helps.

**Comment by kfern** [comment]
Solved!! 

I'll only change the vsg width

![image](https://user-images.githubusercontent.com/1898891/87312313-aec51b80-c520-11ea-93fd-ae69b0d34465.png)

**Comment by Tonywhitemin** [comment]
Hi @pplonski 
I encountered the same issue but my OS is windows10...
I checked the site-packages of graphviz and dtreeviz had been satified as picture below.
Could you give me some advices?
Thanks!
PS: I also have Ubuntu OS and the above solution is worked for me. 
![image](https://user-images.githubusercontent.com/88414200/172323348-dae3584c-b9a9-4a30-a4c5-e4568fbe925e.png)

**Comment by pplonski** [comment]
@Tonywhitemin please try to run `dot -V` to check if `Graphviz` is installed.

**Comment by Tonywhitemin** [comment]
Hi @pplonski
Thanks for your advice, but dot -V couldn't work...
![image](https://user-images.githubusercontent.com/88414200/172523155-a174df7c-78b7-49b9-9486-41c3c454fcb2.png)
Then I tried **pip show graphviz** and **pip show dtreeviz**, it can show the info as following... 
![image](https://user-images.githubusercontent.com/88414200/172523555-ff45afb3-2bc3-4a2f-8628-e8bbde88e787.png)
I also followed the way in https://github.com/parrt/dtreeviz#verify-graphviz-installation like:
1. Download graphviz (version 2.50.0)
2. Update Path environment variable
3. Reboot
But the results of **dot -V** and **where dot** still bad...
Do you have any hint? I'll appreciate it!

**Comment by Tonywhitemin** [comment]
Hi @pplonski
Thanks for your advice, but dot -V couldn't work...
![image](https://user-images.githubusercontent.com/88414200/172541222-c78174db-ba4b-460e-b7d1-c7f26b33d555.png)
Then I tried **pip show graphviz** and **pip show dtreeviz**, it can show the info as following...
![image](https://user-images.githubusercontent.com/88414200/172541523-b1cfee1d-4e00-49c5-8b55-405aa45db5da.png)

I also followed the way in https://github.com/parrt/dtreeviz#verify-graphviz-installation like:

1. Download graphviz (version 2.50.0)
2. Update Path environment variable
3. Reboot
But the results of **dot -V** and **where dot** still bad...

The only way that I can run **dot -V** is following pic.
![image](https://user-images.githubusercontent.com/88414200/172542274-698ddaf8-9f5c-47c9-9f02-e13eb62f18ac.png)
![image](https://user-images.githubusercontent.com/88414200/172541836-091d5afa-e6c2-4651-8792-2f42f331f4da.png)
But it doesn't impact the result...(couldn't generate .svg file) 

Do you have any hint? I'll appreciate it!

**Comment by pplonski** [comment]
You should add a path to `dot` executable to windows environment paths. Then it will work.

**Comment by Tonywhitemin** [comment]
I'll try, thanks for help!
