### ISSUE TITLE
Add EDA for input data set

### ISSUE THREAD

**Issue by pplonski** [mljar/mljar-supervised#125]
It will be nice to have Exploratory Data Analysis (EDA) similar that is in https://mljar.com 
![image](https://user-images.githubusercontent.com/6959032/87848663-9b300100-c8e2-11ea-94a2-5d2c11987a83.png)

The EDA can be saved in a separate Markdown file and have link to it from the main AutoML readme.

**Comment by shahules786** [comment]
I have send a PR @pplonski 
https://github.com/mljar/mljar-supervised/pull/145

**Comment by pplonski** [comment]
For long categoricals there is overflow in the plot
![image](https://user-images.githubusercontent.com/6959032/91188137-3e99e000-e6f1-11ea-9691-2c531090762a.png)

**Comment by pplonski** [comment]
I fixed rotation of x-labels and I change the color of the plots from "blue" to "#007cf2" (this is the color I'm using at https://mljar.com)
