### ISSUE TITLE
Set which iteration is used on learning curve

### ISSUE THREAD

**Issue by pplonski** [mljar/mljar-supervised#132]
Mark the selected iteration (number of trees) on the plot with learning curves.

![image](https://user-images.githubusercontent.com/6959032/88774546-e15b4f00-d183-11ea-91a2-73589a5b8336.png)

**Comment by shahules786** [comment]
Hello @pplonski , Can I work on this issue?

**Comment by pplonski** [comment]
Yes. @shahules786 you can work on it. It will be nice to add info about selected iteration in the markdown report. Maybe below the plot? Keep in mind that not for all algorithms there will be learning curves. For decision tree there will be a bar plot. Please let me know if you know how to start. I can provide detailed instructions what to do if you want. Just let me know. I'llbe back from vacations on Monday. Thanks you!

**Comment by shahules786** [comment]
@pplonski Yes,I would love to get some intro.Meanwhile, I can go through the codebase and familiarize the code.Happy vacation!

**Comment by pplonski** [comment]
In `mljar-supervised` the model can consist of several learners. For example, in the case of 10-fold cross-validation, the model will consist of 10 learners. The learner produces the `learner_{index}_training.log` files with information about metric values for training and validation datasets for each iteration (`index` in the file name is the number of a learner in cross-validation, starting from 1). If such files are created then learning curves are plotted and added to markdown report.

Learning curves are plotted in `supervised/utils/learning_curves.py` file. There is a `plot_iterations` method for plotting learning curves. In this method, you should search for minimum (right now we only minimize the metrics, for classification and regression) and set it as optimal iteration (or tree) number. For each learner please use a different color, the same color that is used for plotting train and validation metrics (`colors` list). This method produces the `learning_curves.png` file which is latter searched during the markdown report creation `supervised/utils/additional_metrics.py` method: `add_learning_curves`.

For now, I don't see easy way to add the info about optimal iterations number in the markdown so let's add it only on the plots.

Maybe try to set alpha in the color to a value smaller than 1 to make it visible but not distract the main info from learning curves. What do you think?

**Comment by shahules786** [comment]
@pplonski Okay, it will be great if you can add more tutorials to the examples folder.

**Comment by pplonski** [comment]
@shahules786 you are right! I would like to add:
- more example of how to solve Kaggle competitions with AutoML
- how to apply AutoML on numer.ai data (encrypted stock data)
- how to integrate AutoML with relational DB (PostgreSQL, MySQL, MS SQL) 

I'm working on better memory management (#127) and restoring the training (#135). Then I would like to focus on examples and tutorials. Also, good docs are missing :/ 

What is more, I added feature to generate `Golden Features` and feature to do feature selection (on any algorithm) - I would like to describe how it works as well.
