### ISSUE TITLE
figure legend shows every folds 

### ISSUE THREAD

**Issue by shahules786** [mljar/mljar-supervised#137]
While plotting the learning curve for the neural network ( iterations > 1) , the figure shows legend as every fold instead of the specific fold which for which the results are recorded.

Code to generate the plot
`a = AutoML(total_time_limit=60,mode='Compete')`

![learning_curves](https://user-images.githubusercontent.com/25312635/89800733-c9ed7000-db4c-11ea-9f58-db555017fb2b.png)

**Comment by pplonski** [comment]
Probably on other folds, there is only one iteration, that's why you don't see it on the plot. Could you try to increase the time limit, maybe to 10 minutes (10*60), time limit is in seconds.

BTW, @shahules786 how have you found this package?

**Comment by shahules786** [comment]
I was doing a lot of research about auto ml opensource packages which are under active development to start contributing. Found this on some website. I think it will be awesome if you can start a slack channel to help contributors kickstart and interact with each other. @pplonski

**Comment by shahules786** [comment]
> Probably on other folds, there is only one iteration, that's why you don't see it on the plot. Could you try to increase the time limit, maybe to 10 minutes (10*60), time limit is in seconds.
Yes,you're right.

**Comment by pplonski** [comment]
@shahules786 good idea, I will set a slack! :)

**Comment by pplonski** [comment]
The slack link https://mljar-supervised.slack.com/join/shared_invite/zt-gkhfsvhw-H6LMKxxV5adeTmn9V7nbZw#/ I will add it to README.md

I'm closing this issue.
