### ISSUE TITLE
Add Notebook with Titanic dataset analysis

### ISSUE THREAD

**Issue by pplonski** [mljar/mljar-supervised#140]
You can find train and test data here: https://github.com/pplonski/datasets-for-start/tree/master/Titanic

**Comment by shahules786** [comment]
I like to work on this. @pplonski

**Comment by pplonski** [comment]
OK, the issue is yours.

**Comment by shahules786** [comment]
I have sent a PR 
https://github.com/mljar/mljar-supervised/pull/141

**Comment by pplonski** [comment]
Thank you!
