### ISSUE TITLE
AutoMlException

### ISSUE THREAD

**Issue by Amri95** [mljar/mljar-supervised#144]
AutoMLException: The algorithm Random Forest is not allowed to use for ML task: multiclass_classification. Allowed algorithms: ['Decision Tree', 'Baseline', 'LightGBM', 'Extra Trees', 'CatBoost', 'Linear', 'Neural Network', 'Nearest Neighbors']

**Comment by pplonski** [comment]
Thank you @Amri95 for reporting! Are you using the latest version of the package?

**Comment by Amri95** [comment]
Hello, Thank you for your response.
I am using version 0.6.0

Could you please explain the Ensemble?

**Comment by pplonski** [comment]
Could you paste some code example to reproduce?

The Ensemble method is based on http://www.cs.cornell.edu/~alexn/papers/shotgun.icml04.revised.rev2.pdf - it is a greedy approach.

**Comment by pplonski** [comment]
@Amri95 could you please provide some code sample, so I can reproduce. Thanks!

**Comment by pplonski** [comment]
I'm closing this issue. I can't reproduce it with the current code from `master`.
