### ISSUE TITLE
Use tree_method='hist' for Xgboost

### ISSUE THREAD

**Issue by tRosenflanz** [mljar/mljar-supervised#15]
Just a suggestion:

Consider using histogram method for Xgboost instead of default 'auto'. See this description:
https://github.com/dmlc/xgboost/issues/1950

In practice it is 5-10x faster and leads to less overfitting. 

Also helpful to limit thread usage to the number of physical  cores of the system instead of  default max virtual cores.

**Comment by pplonski** [comment]
I've set the `tree_method='hist'`. It will be added in new release. Thank you for help! :)
