### ISSUE TITLE
Add ability to pass sample weights for training

### ISSUE THREAD

**Issue by pplonski** [mljar/mljar-supervised#154]
There should be an option to pass weights for training. Weights should be used in metrics as well.

**Comment by spamz23** [comment]
Do you mean `class_weights`? So it pays more "attention" to a certain class in a classification task?

**Comment by pplonski** [comment]
I mean sample weights. For class weights, I've created separate issue https://github.com/mljar/mljar-supervised/issues/155

**Comment by pplonski** [comment]
@kmedved this can be added to the next major release. Would you like to help? Even testing or providing use cases would be nice.

**Comment by kmedved** [comment]
I would be happy to help with testing or use cases; actual code contribution is over my head unfortunately.

**Comment by pplonski** [comment]
User can pass `sample_weight` in the `fit()`:

```
automl = AutoML()
automl.fit(X, y, sample_weight)
```

The default for `sample_weight` is `None`. All metrics (`eval_metric` and additional metrics) use `sample_weight` if available.

The algorithms that don't support `sample_weight`:
- MLP Classfier and Regressor ([docs](https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html#sklearn.neural_network.MLPClassifier.fit))
- kNN Classifier and Regressor ([docs](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html#sklearn.neighbors.KNeighborsClassifier.fit))

**Comment by pplonski** [comment]
@kmedved I just finished `sample_weight` functionality. It is available in the `dev` branch. If you have use cases for testing, I'll be happy to hear feedback from you!

**Comment by kmedved** [comment]
Thanks @pplonski - I will do some testing. Thanks!

**Comment by alitirmizi23** [comment]
@pplonski does adding sample_weight in .fit() cause training to pay more attention to heavily weighted samples or is it just for calculating metrics?

**Comment by pplonski** [comment]
@alitirmizi23 you are right, the higher the weight the more attention during the training.
