### ISSUE TITLE
Add ROC curve for binary classification report

### ISSUE THREAD

**Issue by pplonski** [mljar/mljar-supervised#158]
It will be fantastic to add ROC curve in a `README.md` report file for the model in a binary classification task.

**Comment by spamz23** [comment]
Like this?
![image](https://user-images.githubusercontent.com/49190578/91914608-5ef90a00-ecb0-11ea-9f7a-f021ab490f8a.png)

**Comment by spamz23** [comment]
This could also be extended to Multiclass classification, using a OneVsAll approach.

**Comment by pplonski** [comment]
Looks good!
- what about classes names, if there are no 0,1 class but coded categorically, can we add information which category is positive and which negative?
- It should be extended to multiclass.

I remember that @shahules786 was working on this issue. But the blocker was categorical class names.

**Comment by pplonski** [comment]
How would look the plot if there will be ROC from all data, not a mean?

From what I remember at the end of the training the reported AUC is computed from all available samples using out-of-folds predictions (in case of CV). So it will be good to have on the plot the ROC from all samples, instead of mean - to have consistency in results in the Markdown report and chart.

**Comment by shahules786** [comment]
@spamz23 There is an issue which is blocking further evaluation in working on multi class classification, maybe you can add it for binary classification. What say @pplonski ?

**Comment by pplonski** [comment]
For sure binary class and multi-class issues are connected. If there will be a way to solve it for any case, the other should be straight forward.

**Comment by shahules786** [comment]
Is this still on? If you want I can work on this. @pplonski

**Comment by pplonski** [comment]
Yes, it is available, I assigned you to this issue. Thank you!

**Comment by LukasKaspras** [comment]
@shahules786 Just saw that this issue is still open; can I support you in any way?

**Comment by pplonski** [comment]
@shahules786 @LukasKaspras @spamz23 @partrita thank you for your help! I was able to solve this issue with the `scikit-plot` package https://scikit-plot.readthedocs.io/en/stable/metrics.html Changes will go to the `0.10.4`  version.
