### ISSUE TITLE
Improve memory management on X and y at `fit()`

### ISSUE THREAD

**Issue by spamz23** [mljar/mljar-supervised#165]
Right now `fit()` is saving X and y to the hard drive and deleting the content of X from memory. There should be a better way to handle this.

**Comment by pplonski** [comment]
@spamz23 I'm closing the issue. The local dump to hard drive works. Is it the best solution? are there better solutions? Hard to say.

In the AutoML `fit()` we need to keep an original copy of the data. We can keep it in the RAM or hard drive. Keep in RAM is not a good solution for large datasets and a large number of models. 

Feel free to reopen if you will have any new ideas on how to handle it.
