### ISSUE TITLE
Add link to EDA in main report

### ISSUE THREAD

**Issue by pplonski** [mljar/mljar-supervised#169]
In main `README.md` there should be a link to EDA if it is available.

***Detail desc***:
- in the file `supervised/base_automl.py` there is created main `README.md` for `AutoML` in `select_and_save_best()`
- at the end of this file we can add a link to `Automated Exploratory Data Analysis` if there is `EDA/README.md` file available in `self._results_path`
- We can add in Markdown something like:

```
## Automated Exploratory Data Analysis 

There is Automated EDA available in this [report](EDA/README.md).
```

**Comment by pplonski** [comment]
@tinomaxthayil great! 

Please check:
- contributing guide https://github.com/mljar/mljar-supervised/blob/master/docs/contributing.md
- I would like to see 2 tests for this new code. One test for EDA available and one for missing EDA dir. If you will need help with tests please let me know.

In case of any questions, I'm happy to help.

Good luck!

**Comment by tinomaxthayil** [comment]
Yeah sure. I'll keep you updated.

**Comment by pplonski** [comment]
@LukasKaspras what about this issue? This one is perfect for start.

**Comment by LukasKaspras** [comment]
@pplonski Great! I'll look into it this weekend!

**Comment by pplonski** [comment]
I've added `Go back` links to EDA readme files. Closing.
