### ISSUE TITLE
Bug with SHAP when uses more than 1k samples dataset

### ISSUE THREAD

**Issue by tmdavid** [mljar/mljar-supervised#173]
In order to reproduce the bug:

```
X_train = np.random.uniform(size=(5763, 31))
y_train = np.random.randint(0, 2, size=(5763, ))
​
automl = AutoML()
automl.fit(X_train, y_train)
```

The output will produce this exception:

Exception while producing SHAP explanations. positional indexers are out-of-bounds

If I'm not mistaken the bug can be found in this part: 

https://github.com/mljar/mljar-supervised/blob/fb71ef2b8399ca631d0c5fad58ad7af2d11647dd/supervised/utils/shap.py#L76

**Comment by pplonski** [comment]
@tmdavid you are right the bug was in `get_sample()` method. It is fixed. I've added unit tests for this method. The fix will be in `0.7.1` release which should be today/tomorrow.
