### ISSUE TITLE
unable to predict using existing model after loading

### ISSUE THREAD

**Issue by tmontana** [mljar/mljar-supervised#193]
automl = AutoML(results_path=experiment_name)

preds=automl.predict_all(X_test) generates the below error

This works when using right after training the model but not when loading it down the line.

the file params.json is present in the directory

thanks

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-56-79b2eae7cb76> in <module>
----> 1 preds=automl.predict_all(X_test)

/anaconda/envs/mlj/lib/python3.8/site-packages/supervised/automl.py in predict_all(self, X)
    331 
    332         """
--> 333         return self._predict_all(X)
    334 
    335     def score(self, X, y=None):

/anaconda/envs/mlj/lib/python3.8/site-packages/supervised/base_automl.py in _predict_all(self, X)
    822     def _predict_all(self, X):
    823         # Check is task type is correct
--> 824         if self._ml_task == REGRESSION:
    825             raise AutoMLException(
    826                 f"Method `predict_all()` can only be used when in classification tasks. Current task: '{self._ml_task}'."

AttributeError: 'AutoML' object has no attribute '_ml_task'

**Comment by tmontana** [comment]
Strangely if I start with preds=automl.predict(X_test)

then run

preds=automl.predict_all(X_test)

it all works...

**Comment by pplonski** [comment]
It might be that not all parameters are loaded for `predict_all` ???

Anyway, I have added saving and loading for all parameters of `AutoML` object. So it should work now. I've also removed the constraint that `predict_all` can be used only to classification. Now, it can be used for regression as well (the old behavior).

**Comment by pplonski** [comment]
I'm closing the issue (it should be fixed). If you will see any problems feel free to repopen.

Please use the same version of the package for saving and loading a model.

Changes from this issue will go to the next release - `0.7.3`.
