### ISSUE TITLE
Add docs and examples for Automated EDA and Extended EDA

### ISSUE THREAD

**Issue by pplonski** [mljar/mljar-supervised#198]
Please add docs and examples for EDA. 

The docs are served at this URL: https://supervised.mljar.com/features/eda/

The docs repository: https://github.com/mljar/docs

There should be an example for each feature type with its plot.

**Comment by pplonski** [comment]
Could you please take a look at this issue @shahules786 ?

**Comment by shahules786** [comment]
Yes @pplonski  It can be done ASAP.

**Comment by shahules786** [comment]
hey @pplonski , I have send a PR https://github.com/mljar/docs/pull/2

**Comment by pplonski** [comment]
Merged! Thank you @shahules786 !

**Comment by pplonski** [comment]
Uploaded to the server: https://supervised.mljar.com/features/eda/
