### ISSUE TITLE
problem with predict when multi-class classification

### ISSUE THREAD

**Issue by tmontana** [mljar/mljar-supervised#199]
same for predict, predict_proba and predict_all

preds=automl.predict_proba(X_test)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-81-bc591f705b42> in <module>
----> 1 preds=automl.predict_proba(X_test)

/anaconda/envs/mlj/lib/python3.8/site-packages/supervised/automl.py in predict_proba(self, X)
    312 
    313         """
--> 314         return self._predict_proba(X)
    315 
    316     def predict_all(self, X):

/anaconda/envs/mlj/lib/python3.8/site-packages/supervised/base_automl.py in _predict_proba(self, X)
    878         # If classification task the result is in column 'label'
    879         # Need to drop `label` column.
--> 880         return self._base_predict(X).drop(["label"], axis=1).to_numpy()
    881 
    882     def _predict_all(self, X):

/anaconda/envs/mlj/lib/python3.8/site-packages/supervised/base_automl.py in _base_predict(self, X)
    850             target_is_numeric = self._data_info.get("target_is_numeric", False)
    851             if target_is_numeric:
--> 852                 predictions["label"] = predictions["label"].astype(np.int32)
    853             return predictions
    854         # Regression

/anaconda/envs/mlj/lib/python3.8/site-packages/pandas/core/generic.py in astype(self, dtype, copy, errors)
   5541         else:
   5542             # else, only a single dtype is given
-> 5543             new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors,)
   5544             return self._constructor(new_data).__finalize__(self, method="astype")
   5545 

/anaconda/envs/mlj/lib/python3.8/site-packages/pandas/core/internals/managers.py in astype(self, dtype, copy, errors)
    593         self, dtype, copy: bool = False, errors: str = "raise"
    594     ) -> "BlockManager":
--> 595         return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
    596 
    597     def convert(

/anaconda/envs/mlj/lib/python3.8/site-packages/pandas/core/internals/managers.py in apply(self, f, align_keys, **kwargs)
    404                 applied = b.apply(f, **kwargs)
    405             else:
--> 406                 applied = getattr(b, f)(**kwargs)
    407             result_blocks = _extend_blocks(applied, result_blocks)
    408 

/anaconda/envs/mlj/lib/python3.8/site-packages/pandas/core/internals/blocks.py in astype(self, dtype, copy, errors)
    592             vals1d = values.ravel()
    593             try:
--> 594                 values = astype_nansafe(vals1d, dtype, copy=True)
    595             except (ValueError, TypeError):
    596                 # e.g. astype_nansafe can fail on object-dtype of strings

/anaconda/envs/mlj/lib/python3.8/site-packages/pandas/core/dtypes/cast.py in astype_nansafe(arr, dtype, copy, skipna)
    965         # work around NumPy brokenness, #1987
    966         if np.issubdtype(dtype.type, np.integer):
--> 967             return lib.astype_intsafe(arr.ravel(), dtype).reshape(arr.shape)
    968 
    969         # if we have a datetime/timedelta array of objects

pandas/_libs/lib.pyx in pandas._libs.lib.astype_intsafe()

ValueError: invalid literal for int() with base 10: '1.0'

**Comment by pplonski** [comment]
Looks like a bug. Thank you for reporting.

@tmontana could you please provide the information about classes that are used in the target? Are they strings, for example "class_1", "class_2", "class_3", ... or other format of the target?

**Comment by tmontana** [comment]
here's a snapshot for y (they're float64)

0         5.0
1         2.0
2         5.0
3         4.0
4         5.0
         ... 
813296    5.0
813297    5.0
813298    4.0
813299    4.0
813300    1.0
Name: P360d_5_Cats, Length: 813301, dtype: float64

**Comment by tmontana** [comment]
from 1 to 5

**Comment by pplonski** [comment]
Got it! Thank you! I will fix it soon.

You can try to cast the target to `int` and it should fix the problem

```py
df[target] = df[target].astype(int)
```

**Comment by tmontana** [comment]
will do thanks.  automl._best_model.predict(X_test) also works fyi

**Comment by pplonski** [comment]
Fixed. It will be in the next release `0.7.3`
