### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by partrita** [mljar/mljar-supervised#202]
```python
from supervised.automl import AutoML
```

```bash
     11 import matplotlib.pyplot as plt
     12 from colour import Color, rgb2hex
---> 13 from graphviz.backend import run, view
     14 from sklearn import tree
     15 from typing import Mapping, List, Tuple
ImportError: cannot import name 'run' from 'graphviz.backend' 
```

I've tried `pip install --upgrade graphviz>=0.9` but still got same error.

**Comment by pplonski** [comment]
Thank you @partrita for reporting the problem. Could you tell me what operating system are you using? I will try to reproduce the problem.

**Comment by partrita** [comment]
My OS is Ubuntu 20.04. Python version is 3.8

```bash
$python3 -m venv venv
$source venv/bin/activate
$(venv)pip install mljar-supervised
```

I got bunch of error message like this.

```bash
  Building wheel for mljar-supervised (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /mnt/c/Users/partr/Documents/mljar/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zoezu34d/mljar-supervised/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zoezu34d/mljar-supervised/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-uh4cobv0
       cwd: /tmp/pip-install-zoezu34d/mljar-supervised/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help

  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for mljar-supervised
```

I've tried install `pip install wheel` but still got same error.

**Comment by pplonski** [comment]
Hmmm, I didn't test it on python 3.8, but it should work (I will add 3.8 to travis ci).

Can you check this post https://stackoverflow.com/questions/34819221/why-is-python-setup-py-saying-invalid-command-bdist-wheel-on-travis-ci maybe it will help?

**Comment by partrita** [comment]
Problem solved!  The command below was so obvious but it is worth to mention on install guide.

```bash
apt-get install -y build-essential python3-dev
```

![](https://i.imgur.com/cedfOjo.png)

It seems like a better way to distribute it as a Docker image. The simple `dockerfile` I wrote is as follows.

```docker
FROM python:3.7-slim-buster
RUN apt-get update && apt-get -y update
RUN apt-get install -y build-essential python3-pip python3-dev
RUN pip3 -q install pip --upgrade
RUN pip3 install mljar-supervised jupyter
CMD ["jupyter", "notebook", "--port=8888", "--no-browser", "--ip=0.0.0.0", "--allow-root"]
```

Thank you for making such a awesome python library.

**Comment by pplonski** [comment]
@partrita you are my hero for today!

**Comment by madpower2000** [comment]
The same problem with MLJAR Studio Desktop Application

**Comment by pplonski** [comment]
@madpower2000 if the problem is related to MLJAR Studio, please add issue there https://github.com/mljar/studio/issues

Please also give details about your operating system and it will be great to have screenshots with problem.
