### ISSUE TITLE
Percentiles are 0 for discrete features in EDA

### ISSUE THREAD

**Issue by pplonski** [mljar/mljar-supervised#207]
Percentiles values are 0 for discrete features in EDA

Example:
```
Feature : feat_65
Feature type : discrete
Missing : 0.0%
Unique : 25
Count :61878.0
Mean :0.22222760916642426
Std :0.7830520119515331
Min :0.0
25%th Percentile : 0.0
50%th Percentile : 0.0
75%th Percentile : 0.0
```

@shahules786 could you please take a look at it?

**Comment by shahules786** [comment]
@pplonski sure

**Comment by shahules786** [comment]
There seem to be 61k samples in the dataset and only 25 unique values for the feature. By looking at the mean value we can say that most of the value is zero for the feature. So I think 25,50,75th percentile is 0.0 only. It should be correct. @pplonski 
you can do `df[feat_65].describe()` to cross-check.

**Comment by pplonski** [comment]
Thank you @shahules786 for checking!
