### ISSUE TITLE
Minor class in multi-class classification with too few samples to stratify

### ISSUE THREAD

**Issue by pplonski** [mljar/mljar-supervised#215]
In the case of too few samples to perform stratification there is an error thrown:

```py
The least populated class in y has only 2 members, which is less than n_splits=5.
```

Maybe we can detect such situations and upsample minor classes? For sure it is related to https://github.com/mljar/mljar-supervised/issues/157 However, this issue requires rather a quick fix and #157 requires a larger treatment of unbalanced datasets.

**Comment by shahules786** [comment]
Should auto ml do upsampling w/o the user concern? Anyway, the model isn't going to learn anything for that class. Isn't it better to inform the user through a warning that stratification is not possible? @pplonski

**Comment by pplonski** [comment]
I've added a function `_handle_drastic_imbalance()` that assures that there is always at least 20 (or `k_folds` if set) samples per class.
