### ISSUE TITLE
Why isn't Python3.8 not supported?

### ISSUE THREAD

**Issue by kurianbenoy** [mljar/mljar-supervised#220]
- Just curious why is not mljar supporting Python3.8 and recently released python3.9

**Comment by pplonski** [comment]
@kurianbenoy that's a good question! I've added 3.8 and 3.9. 

Travis CI doesn't support 3.9 yet, so I need to set 3.9-dev for now.

**Comment by pplonski** [comment]
After running Travis it looks like not all packages are ready for 3.9 (for now I not adding it). I've added support for 3.8.

Changes will be in the `0.7.4` release.
