### ISSUE TITLE
Folder naming incosistency in dist-packages

### ISSUE THREAD

**Issue by mglowacki100** [mljar/mljar-supervised#222]
This is a minor issue but in `usr/local/lib/python.../dist-packages` there are folders `mljar_supervised-0.7.3.dist-info` and `supervised`. To be consistent with other folders naming convention: `supervised` should be renamed to `mljar_supervised`.

**Comment by pplonski** [comment]
Does it need to be consistent? The `mljar-supervised` is the name of the package, `supervised` is the directory with code. I will leave it as it is for now.
