### ISSUE TITLE
Repeated k-folds validation [enhancement]

### ISSUE THREAD

**Issue by mglowacki100** [mljar/mljar-supervised#223]
Please add repeated k-fold validation
https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.RepeatedKFold.html#sklearn.model_selection.RepeatedKFold

**Comment by pplonski** [comment]
Need to check how to use/implement predictions from a repeated CV in the Ensemble and Ensemble stacking

**Comment by pplonski** [comment]
- There is no change in Ensemble and Ensemble stacking. 
- If validation is repeated, then for computing out-of-folds (OOF) predictions we compute the average over all repeats. 
- For computing predictions on test data, we average over all learners (all folds and all repeats).
- There will be a `repeat` parameter in the `validation_strategy` argument that will control the number of repeats:

```py
AutoML(validation_strategy= {
        "validation_type": "kfold",
        "k_folds": 3,
        "stratify": True,
        "shuffle": True,
        "repeat": 4
      }
)
```

Need to add tests.

**Comment by pplonski** [comment]
The repeated validation shouldnt be used with stacking.
