### ISSUE TITLE
Installation fails in Anaconda on Windows 10

### ISSUE THREAD

**Issue by hajimurtaza** [mljar/mljar-supervised#225]
What I tried:

`pip install mljar-supervised`

Error Message:
Posted on this question on [stackoverflow](https://stackoverflow.com/questions/64773160/error-installing-fastparquet-in-windows-10/64773445#64773445). 

Current Status:
There is an [ongoing issue](https://developercommunity.visualstudio.com/content/problem/1207405/fmod-after-an-update-to-windows-2004-is-causing-a.html) with Numpy 1.19.4 which is currently being investigated by Microsoft.  Downgrading to Numpy 1.19.3 helps bypassing this issue as mentioned in this [answer.](https://developercommunity.visualstudio.com/solutions/1241964/view.html)

**Comment by pplonski** [comment]
I've updated `numpy>=1.20.0` so it should be no problem now.
