### ISSUE TITLE
strings in golden_features.json

### ISSUE THREAD

**Issue by SuryaThiru** [mljar/mljar-supervised#227]
The golden features JSON file that is being saved by mljar contains strings for `new_features` and  `new_columns` instead of dictionaries which makes it a little difficult to view/parse the file.

**Current output:**
![image](https://user-images.githubusercontent.com/22935226/99356732-a61a9280-28d0-11eb-9376-c426f57a48be.png)

**Expected output:**
![image](https://user-images.githubusercontent.com/22935226/99357105-5dafa480-28d1-11eb-857e-b40c2f17b7ea.png)

We can avoid [using the indented JSON string here](https://github.com/mljar/mljar-supervised/blob/821500de420a35700f10d0a3126e01ab9d6fffc0/supervised/preprocessing/goldenfeatures_transformer.py#L197) while saving the model unless there is some  other specific reason to do so.

**Comment by pplonski** [comment]
Hey @SuryaThiru! You are right, the indent is not needed here. Would you like to PR?

**Comment by SuryaThiru** [comment]
Yes, I can do that.

**Comment by pplonski** [comment]
@SuryaThiru thank you! Good fix!
