### ISSUE TITLE
Leaderboard not sorted by metric value

### ISSUE THREAD

**Issue by SuryaThiru** [mljar/mljar-supervised#229]
The leaderboard tables in the output leaderboard.csv and the README.md are not sorted by the metric value. It will be convenient to compare and review our models if they are sorted.

Is there a way to identify if the metric is `greater_is_better` from this [method](https://github.com/mljar/mljar-supervised/blob/821500de420a35700f10d0a3126e01ab9d6fffc0/supervised/base_automl.py#L186)?

**Comment by pplonski** [comment]
Right now, the models appear on the leaderboard in the order in which they were trained.

We can add sorting in `get_leaderboard()` but please add a method in the `Metric` class that will return the direction of sorting.

@SuryaThiru would you like to PR on this issue?

**Comment by SuryaThiru** [comment]
Is a `Metric` class object accessible from `get_leaderboard()` ? I only noticed the metric names being used.
