### ISSUE TITLE
Predicting probability for all models

### ISSUE THREAD

**Issue by agosiewska** [mljar/mljar-supervised#24]
Hello,
great AutoML tool!
But I have encountered a problem.

When the final model is `RF`, predict function returns classes (values are equal to 0 or 1).
But for other models (`CatBoost`, `Xgboost`, `LightGBM`, `NN`) , predict function returns probabilities.
Is it possible to get probabilities when the best model is Random Forest?

**Comment by pplonski** [comment]
Hey Alicja!
Thanks for reporting. Could you please provide code sample? Might be a bug!

**Comment by agosiewska** [comment]
Sorry for bothering you, that was my fault.
I was testing on a training data, so Random Forest was overfitted and it returned probabilities, but equal 0 and 1.
I will close this issue.

**Comment by pplonski** [comment]
OK :) Have you been able to get a good model?

**Comment by agosiewska** [comment]
Yes and no :)
I was trying to beat h2o AutoML, but results for both frameworks look almost the same.
- 1h time limit AUC was:
    - h2o: 0.7883
    - MLJAR: 0.7818
- 8h time limit:
    - h2o: 0.7866
    - MLJAR: 0.7891

I think maybe it is impossible to achieve more on this dataset. I was training model on FICO data from this [XAI competition](https://community.fico.com/s/explainable-machine-learning-challenge?tabset-3158a=2).

Thank you for developing this AutoML framework, I will definitely be using it in the future!
