### ISSUE TITLE
There is a problem with Learning curves plots. They have wrong y-axis label.

### ISSUE THREAD

**Issue by pplonski** [mljar/mljar-supervised#248]
There is a problem with Learning curves plots. They have wrong y-axis label.

**Comment by LukasKaspras** [comment]
@pplonski What would you want/expect as y-axis label? I would be open to look into this!

**Comment by pplonski** [comment]
The metric used by learner is on y-axis label in the learning curve plot. 

The metric used by learner can be different than `eval_metric` used to compare models.
