### ISSUE TITLE
Does it work with regression problem?

### ISSUE THREAD

**Issue by ArioBattolla** [mljar/mljar-supervised#26]
Does it work with regression problem? Because when I try to use, it considers labels as classes.
Could you show me a regression example in python?

**Comment by pplonski** [comment]
The regression task is not yet implemented. I'm working on it. Should be available in next 1-2 months.

**Comment by JonathanLehner** [comment]
would be good to make this clear in the documentation :O

**Comment by pplonski** [comment]
@ArioBattolla @JonathanLehner I've added support for regression. I need to add more metrics (additional metrics #41) However the package should work on regression problems.
