### ISSUE TITLE
RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config

### ISSUE THREAD

**Issue by feacluster** [mljar/mljar-supervised#260]
I receive the error below when installing via:

 pip3 install --user mljar-supervised

  Found existing installation: llvmlite 0.31.0
    Uninstalling llvmlite-0.31.0:
      Successfully uninstalled llvmlite-0.31.0
  Running setup.py install for llvmlite ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-htvogqcg/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-oib1dz19-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    got version from file /tmp/pip-build-htvogqcg/llvmlite/llvmlite/_version.py {'version': '0.35.0', 'full': 'ea23b026930cc00824c907172383f54c9d438e6b'}
    running build_ext
    /usr/bin/python3 /tmp/pip-build-htvogqcg/llvmlite/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/tmp/pip-build-htvogqcg/llvmlite/ffi/build.py", line 105, in main_posix
        out = subprocess.check_output([llvm_config, '--version'])
      File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
        **kwargs).stdout
      File "/usr/lib64/python3.6/subprocess.py", line 423, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
        restore_signals, start_new_session)
      File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config': 'llvm-config'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/tmp/pip-build-htvogqcg/llvmlite/ffi/build.py", line 191, in <module>
        main()
      File "/tmp/pip-build-htvogqcg/llvmlite/ffi/build.py", line 181, in main
        main_posix('linux', '.so')
      File "/tmp/pip-build-htvogqcg/llvmlite/ffi/build.py", line 108, in main_posix
        "to the path for llvm-config" % (llvm_config,))
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/usr/bin/python3' failed with exit status 1

    ----------------------------------------
  Rolling back uninstall of llvmlite
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-htvogqcg/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-oib1dz19-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-htvogqcg/llvmlite/

**Comment by pplonski** [comment]
Never seen such an error before. What operating system are you using?

**Comment by pplonski** [comment]
I got a similar error. Please try to upgrade pip:

```
pip install --upgrade pip
```

The issue is related to fastparquet installation, please see discussion: https://github.com/numba/llvmlite/issues/621

**Comment by feacluster** [comment]
Thanks. I actually found a workaround by installing on another system. The error came from this system:

RHEL 7.8
Python 3.6.8 (default, Sep 26 2019, 11:57:09)

**Comment by pplonski** [comment]
@feacluster would you be able to get a good ML model?

**Comment by feacluster** [comment]
> 
> 
> @feacluster did you get a good ML model?

Unfortunately, I do not much about ML. I am just our cluster admin :-)
