### ISSUE TITLE
Error in kaggle notebook kernel

### ISSUE THREAD

**Issue by pplonski** [mljar/mljar-supervised#308]
There is problem with pyarrow verion in kaggle notebook. There is an error:

```py
 [Errno 2] No such file or directory: 'AutoML_1/y.parquet'
```

See kaggle comment for details: https://www.kaggle.com/mt77pp/mljar-autoeda-automl-prediction/comments#1197484

**Comment by pplonski** [comment]
- removed `fastparquet` dependency
- updated `pandas` package
- remove support for Python 3.6

**Comment by hokmingkwan** [comment]
Hi, I've encountered the same issue and tried the solution you mentioned. However, it still doesn't work. Would you give me your thoughts?

**Comment by pplonski** [comment]
@hokmingkwan please start with fresh notebook (not copy or fork of existing one) and try to install mljar directly from the github:

```
!pip install -q -U git+https://github.com/mljar/mljar-supervised.git@master
```

**Comment by hokmingkwan** [comment]
> @hokmingkwan please start with fresh notebook (not copy or fork of existing one) and try to install mljar directly from the github:
> 
> ```
> !pip install -q -U git+https://github.com/mljar/mljar-supervised.git@master
> ```
@pplonski I have already tried that start with fresh notebook, but still keeps failing with same error 

`FileNotFoundError: [Errno 2] No such file or directory: 'AutoML_1/y.parquet'`

**Comment by pplonski** [comment]
@hokmingkwan I've just checked: https://www.kaggle.com/mt77pp/let-me-check

In the fresh notebook it will work. For forked/copy notebooks there might be a problem with numpy versions -> that's why errors.

**Comment by pplonski** [comment]
@hokmingkwan do you have link for your notebook? What dataset are you trying to analyze?

**Comment by hokmingkwan** [comment]
> @hokmingkwan do you have link for your notebook? What dataset are you trying to analyze?

@pplonski I found out what causes the error. For example, you have a large csv dataset with all numeric data and you read the csv by pandas. So you have a dataframe and would like to reduce the memory usage, you may change the data type to np.float16, `ie. df = df.astype(np.float16)`
if you run `model.fit(df.iloc[:, :-1], df.iloc[:, -1:])`
Then it will show this error:
`FileNotFoundError: [Errno 2] No such file or directory: 'AutoML_1/y.parquet'`

**Comment by pplonski** [comment]
@hokmingkwan thank you! You are right! I will fix it ...

What dataset were you analyzing?

**Comment by hokmingkwan** [comment]
> @hokmingkwan thank you! You are right! I will fix it ...
> 
> What dataset were you analyzing?

@pplonski My dataset is very like your example, but I use `sklearn.datasets.make_regression(n_samples=1000000, n_features=200)` and convert it to pandas df. 
Because I would like to explore and experience automl with mljar.

**Comment by pplonski** [comment]
@hokmingkwan it should work right now, I've added backup data read/write to CSV in the case of parquet problems.

Please install the package from GitHub:
```
!pip install -q -U git+https://github.com/mljar/mljar-supervised.git@master
```

**Comment by hokmingkwan** [comment]
> @hokmingkwan it should work right now, I've added backup data read/write to CSV in the case of parquet problems.
> 
> Please install the package from GitHub:
> 
> ```
> !pip install -q -U git+https://github.com/mljar/mljar-supervised.git@master
> ```

@pplonski After I install the package from GiHub and import the package `from supervised.automl import AutoML`
I encountered this error
`ModuleNotFoundError: No module named 'supervised.utils.additional_plots'`

**Comment by pplonski** [comment]
@hokmingkwan sorry!!! I've added more plots for models and forgot to add a file and package - sorry!

It is fixed and CI build is proceeding.

**Comment by hokmingkwan** [comment]
> @hokmingkwan sorry!!! I've added more plots for models and forgot to add a file and package - sorry!
> 
> It is fixed and CI build is proceeding.

@pplonski  no worries! I successfully import the package, thanks!
