### ISSUE TITLE
Documentation: How does mljar-supervised work?

### ISSUE THREAD

**Issue by juliuskittler** [mljar/mljar-supervised#317]
Thanks for your great work! `mljar-supervised` is a library I won't hesitate to recommend to others.

There is one aspect that's missing for me though: A publication or thorough description of what is going on under the hood. Other solutions such as `auto-sklearn` are very transparent about their underlying algorithm. Example: https://www.automl.org/wp-content/uploads/2018/12/auto-sklearn-1.pdf (in particular p. 125-126).

Do you have any plans to summarize the underlying algorithm of `mljar-supervised` in a similar way? E.g. how are parameters initialized (model types and hyperparameters); which optimization algorithms are used; how are model selection, feature selection, hyperparameter tuning combined; which models are included in the stacked ensemble etc.? Many thanks again for your efforts.

**Comment by pplonski** [comment]
@juliuskittler thank you! Do you get good ML models with MLJAR? 

I agree there is a huge need for better documentation. There is documentation available at https://supervised.mljar.com/ but it needs a heavy update.

**Comment by juliuskittler** [comment]
@pplonski, yes MLJAR did fit good models on my particular problem.

Right, I've seen https://supervised.mljar.com . It's a nice documentation for getting an overview and getting started. However, it lacks a thorough step-by-step description of overall algorithm.

**Comment by juliuskittler** [comment]
Thank you @pplonski. That is already helpful! Also, I'm looking forward to a potential scientific publication.
