### ISSUE TITLE
Problems when loading a stacked ensemble

### ISSUE THREAD

**Issue by RafaD5** [mljar/mljar-supervised#318]
I installed the dev branch yesterday and trained a model with the following parameters
```
automl = AutoML(
    mode='Perform', 
    results_path=str(model_dir),
    total_time_limit=60*60*16,
    eval_metric='mape',
    stack_models=True
)
```

But when I try to load the trained model I get an error. The best model is an Ensemble_Stacked and there is no file Ensemble_Stacked/framework.json. I went to the file best_model.txt and replaced Ensemble_Stacked to Ensemble and it did load that model, but then I got another error:
![image](https://user-images.githubusercontent.com/37419841/108384662-f60f3b00-71d8-11eb-8013-5386aff79582.png)

**Comment by pplonski** [comment]
That's because of an update in the Xgboost package. There is a need to retrain the AutoML. Apologize for this! I'm doing a lot of changes in the package. That's why the package is not backward compatible.

**Comment by RafaD5** [comment]
I trained with the new version of mljar but to load the model I was using my local version. I'm sorry!
