### ISSUE TITLE
How do I cite your project for my paper as I couldn't find any paper on it.

### ISSUE THREAD

**Issue by kingabzpro** [mljar/mljar-supervised#334]
I have been looking for citation but I think there is none so can you send me link of the paper

**Comment by pplonski** [comment]
@kingabzpro we don't have the paper yet. You can cite MLJAR as below:

```
MLJAR: State-of-the-art Automated Machine Learning Framework for Tabular Data, https://github.com/mljar/mljar-supervised, version 0.9.1, 2021
```

**Comment by pplonski** [comment]
MLJAR is still under active development. Last week we added Optuna integration, which improves results a lot on many datasets. Example: https://www.kaggle.com/mt77pp/mljar-automl-tps-mar2021

I hope at some time we will create the official article about MLJAR, I believe it has many innovative features.

**Comment by tresoldi** [comment]
Sorry for reopening the issue, but for a full citation I would need (1) authors, (2) address, and (3) publisher. For publisher I can use "MLJAR" or something similar, but I am not sure about the other two.

From the webpage, the blog and some documentation, it seems the "author" field should be "Piotr Płoński and Aleksandra Płońska" (in this order), and the address should be Wrocław. Is this correct?

**Comment by pplonski** [comment]
@tresoldi sorry that we don't have an official paper yet. Working on that.

Missing info:
Authors: Aleksandra Płońska and Piotr Płoński
Address: Łapy, Poland

**Comment by kingabzpro** [comment]
Thank you, I was going to submit my paper on April 30 and I just updated on Mendeley. Thanks again for amazing new features especially optuna integration.

**Comment by kingabzpro** [comment]
Thank you, I was going to submit my paper on April 30 and I just updated on mendeley. Thanks again for amazing new features especially optuna integration.

> MLJAR is still under active development. Last week we added Optuna integration, which improves results a lot on many datasets. Example: https://www.kaggle.com/mt77pp/mljar-automl-tps-mar2021
> 
> I hope at some time we will create the official article about MLJAR, I believe it has many innovative features.

I have been following your work on Kaggle, its quite good.

**Comment by kingabzpro** [comment]
Do you have citation key?

**Comment by tresoldi** [comment]
Great, thanks! And @kingabzpro is right, amazing work! For reference to others, I will use the following Bibtex entry

```bibtex
@misc{mljar,
  author    = {Aleksandra P\l{}o\'{n}ska and Piotr P\l{}o\'{n}ski},
  year      = {2021},
  publisher = {MLJAR},
  address   = {\L{}apy, Poland},
  title     = {MLJAR: State-of-the-art Automated Machine Learning Framework for Tabular Data.  Version 0.9.1},
  url       = {https://github.com/mljar/mljar-supervised}
}
```
