### ISSUE TITLE
ModuleNotFoundError: No module named 'supervised.tuner.optuna'

### ISSUE THREAD

**Issue by Promisery** [mljar/mljar-supervised#338]
I'm using kaggle notebooks, so I have to use pip to install mljar every time in the notebook. Now when I run `!pip install mljar-supervised` and use AutoML to train my model I get this error.

**Comment by Promisery** [comment]
To reproduce:
```
!pip install mljar-supervised
from supervised.automl import AutoML
```

**Comment by pplonski** [comment]
@Promisery thank you for reporting. Looks like I forgot the `__init__.py` file. It should be fixed now. Could you please install mljar with the following command:

```
!pip install -q -U git+https://github.com/mljar/mljar-supervised.git@master
```

BTW, in which Kaggle competition are you participating?

**Comment by pplonski** [comment]
I've uploaded next release `0.10.1` to PyPi so the following should work as well:

```
pip install mljar-supervised
```

**Comment by Promisery** [comment]
> 
> 
> I've uploaded next release `0.10.1` to PyPi so the following should work as well:
> 
> ```
> pip install mljar-supervised
> ```

It worked, thank you!
I'm in Tabular Playground Series March, mljar helped me a lot

**Comment by pplonski** [comment]
Great. I've made a public kernel with MLJAR on TPS-Mar21 data: https://www.kaggle.com/mt77pp/mljar-automl-tps-mar2021
