### ISSUE TITLE
Python 3.9 and wordcloud

### ISSUE THREAD

**Issue by rterbush** [mljar/mljar-supervised#339]
Any chance of letting dependencies move forward to wordcloud 1.8.1? I think this would allow support of python 3.9.

**Comment by pplonski** [comment]
@rterbush thank you for pointing this. I've updated `wordcloud` and `joblib` packages and it looks that we can run AutoML on Python 3.9 :) Thank you!

Link to Travis build:
https://travis-ci.org/github/mljar/mljar-supervised/builds/763235970

I will add the next release `0.10.2` soon.
