### ISSUE TITLE
When trying to import AutoML it aborts

### ISSUE THREAD

**Issue by Wheaties466** [mljar/mljar-supervised#35]
```
>>> import pandas as pd
>>> from supervised.automl import AutoML
/root/python/MLwebsite/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
Aborted

```

this takes about 30 seconds to complete and ends in me returning to bash and not python. I am just attempting to run the quick example in the readme and I have python 3.6.3 in a brand new venv with nothing but this installed via pip.

**Comment by pplonski** [comment]
Can you paste full code? Which system are you using?

**Comment by Wheaties466** [comment]
```
import pandas as pd
from supervised.automl import AutoML

df = pd.read_csv("https://raw.githubusercontent.com/pplonski/datasets-for-start/master/adult/data.csv", skipinitialspace=True)

X = df[df.columns[:-1]]
y = df["income"]

automl = AutoML()
automl.fit(X, y)

predictions = automl.predict(X)
```
I just remembered I had this issue with tdqm and had to upgrade to 4.33.0

https://github.com/tqdm/tqdm/issues/555

Would this cause the abort I am seeing. I couldn't import the files without upgrading.

**Comment by pplonski** [comment]
Yes, that might be the issue. Please see this PR https://github.com/mljar/mljar-supervised/pull/30/commits/c3363c4753cd8bc33b8549d935f96ab2752cd44b with "tqdm>=4.33"

**Comment by Wheaties466** [comment]
It did seem to work with python 3.7.3 on my laptop so the issue may just be with python 3.6. I will debug further tomorrow.
