### ISSUE TITLE
Add support to google Colab

### ISSUE THREAD

**Issue by pplonski** [mljar/mljar-supervised#352]
Maybe it is possible to display the AutoML report as in pandas-profiling package?

https://github.com/pandas-profiling/pandas-profiling

AutoML reports work with Kaggle notebook https://www.kaggle.com/mt77pp/mljar-automl-bnp-claims-management but in google colab `automl.report()` returns the error: "localhost refused to connect".

**Comment by neel04** [comment]
is there any workaround for this? from what I skimmed over, AutoML does create `report.md` files which can be used to open and read it anytime and see the graphs + extra information there only.

**Comment by pplonski** [comment]
To fix this I think we need to read all reports and display them from memory, not from files. A similar approach is used in pandas-profiling reports.

**Comment by pplonski** [comment]
The report is translated from markdown to HTML, loaded into memory, and displayed in the notebook. Should work with all notebook types.

**Comment by pplonski** [comment]
EDA link is not working ...

**Comment by pplonski** [comment]
OK, fixed. Should work.
