### ISSUE TITLE
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

### ISSUE THREAD

**Issue by RafaD5** [mljar/mljar-supervised#355]
Hello,

I installed the latest version of MLJAR (0.10.2). When I import the package the following error arrises

> RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

I created a new enviroment for the installation with conda. The steps I followed for the installation were:
```
conda create -n mljar39 python=3.9
conda activate mljar39
pip install mljar-supervised
```

Then I run `from supervised.automl import AutoML` and got the RuntimeError

Then, as suggested in this [issue](https://github.com/freqtrade/freqtrade/issues/4281), I updated numpy (explanation [here](https://stackoverflow.com/questions/49756080/opencv-numpy-issue-module-compiled-against-api-version-x-but-this-version-of-n)) but got the following error
![image](https://user-images.githubusercontent.com/37419841/112657711-af88ae00-8e20-11eb-884b-966a2d8fdce1.png)

And now, when I import MLJAR the error does not longer arise and I can use MLJAR, but I don't know if this solution is reliable.

**Comment by pplonski** [comment]
@RafaD5 I believe that there is a small mismatch between numpy versions for some packages. I've added `Optuna` to MLJAR and it doesn't support the newest numpy version. 

The package will work even with the warning. I observed the warning on Ubuntu 16.04 but for Ubuntu 20.04 it works without warning. Hard to point exact fix. However, the numpy update should help.

I would recommend waiting for an update on the Optuna package.

**Comment by xuzhang5788** [comment]
I used the same method to create a conda env. I update mljar-supervided with pip install -U mljar-supervised. When I ran from supervised.automl import AutoML, I still got 
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
My Ubuntu is 20.04

**Comment by pplonski** [comment]
I've updated Optuna (2.7.0) and Numpy (>=1.20.0) packages in `requirements.txt`. The warning should disappear.

**Comment by CyFeng16** [comment]
If you are getting above error in python3.8 environment, python3.7 works fine.
