### ISSUE TITLE
Do you used the whole training data to finalize the models?

### ISSUE THREAD

**Issue by xuzhang5788** [mljar/mljar-supervised#365]
After you did cross-validation, normally we need to use the whole training data to retrain the model and save it for unseen data. When you output the final results, did you retrain the model? If not, it is a kind of a waste of validation data. Thanks.

**Comment by pplonski** [comment]
@xuzhang5788 there is no retraining. For example, if we have a 10-fold CV we have 10 models as the final results. All 10 models are used for computing predictions and the final prediction is the average.

**Comment by xuzhang5788** [comment]
Thank you!
