### ISSUE TITLE
Unable to save additional metrics due to encoding issues

### ISSUE THREAD

**Issue by tresoldi** [mljar/mljar-supervised#368]
When the encoding of data (such as feature names) does not match the one of the system (for example, when data is encoded with `utf-8` under many Windows systems), additional metrics cannot be saved, raising issues such as:

```
2021-04-04 15:52:32,312 supervised.utils.additional_metrics ERROR Exception while saving additional metrics. 'charmap' codec can't encode character '\u025b' in position 78: character maps to <undefined>
```

`mljar` is smart enough to just skip over the exception, so it is not such a big problem, but it limits usefulness particularly for data exploration.

A fix could be to have the `.save_*` methods of `AdditionalMetrics` (supervised/utils/additional_metrics.py) accept an encoding. A "good enough" alternative might be to explicitly add an `encoding="utf-8"` to all such methods, noting it in the documentation as the default encoding.

**Comment by pplonski** [comment]
@tresoldi thank you for reporting. Could you please provide code with data to reproduce this issue?

**Comment by pplonski** [comment]
@tresoldi I've added `encoding="utf-8"` to all save methods in `AdditionalMetrics` module. Should work now. Thank you for your help!
