### ISSUE TITLE
install fail: building wheel for shap(setup.py)  

### ISSUE THREAD

**Issue by xinyue00766** [mljar/mljar-supervised#369]
hi, everyone
When I was installing mljar-supervised, I got some errors, that seem like related to the building wheel for shap when installing requirements.txt. 
I have tried three different methods to install:
(1)From PyPi repository
(2)From source code
(3)Installation for development
The same problem happened as follows:
![image](https://user-images.githubusercontent.com/16629903/114129864-feab0480-9931-11eb-8e83-f5dac95182f2.png)

I'm using python3.7 on Ubuntu 16.04

**Comment by pplonski** [comment]
are you able to install `shap` package alone?

**Comment by xinyue00766** [comment]
I have tried to "pip install shap" to install shap, but failed.
I have searched the same problem on the installation of shap, and used "pip install shapely", shapely can be installed successfully but the above problem still happened

**Comment by pplonski** [comment]
@xinyue00766 you need to install `shap` package. This one https://github.com/slundberg/shap

Sometime you need to install `graphviz` with `apt`:

```
sudo apt install graphviz
```

**Comment by xinyue00766** [comment]
Thanks! I have solved the problem and install mljar-supervised successfully.
