### ISSUE TITLE
Do you save the dataset file name somewhere in the results_path folder?

### ISSUE THREAD

**Issue by xuzhang5788** [mljar/mljar-supervised#370]
After training, I want to know which dataset I used during training. I couldn't find this information. If you didn't save this information, please add it.

**Comment by pplonski** [comment]
I can add a method that will allow the user to add any information to the report. The proposed example:

```python
automl = AutoML()
automl.fit(X, y)
msg = "Training file name: my_file.csv"
automl.report_append(msg)
```

Where the `msg` can be any string. I can add the `# Additional information` section in the main AutoML `README.md`.

Would it work for you?

**Comment by xuzhang5788** [comment]
@pplonski Thank you. It is great!
However, it will be great if it can be automatically added into data _infor.json. Maybe users have to add msg manully.

**Comment by pplonski** [comment]
Yes, I think you will need to add this manually. Or you can write some custom code, to append your info in report files.
