### ISSUE TITLE
How to reuse the trained algorithms?

### ISSUE THREAD

**Issue by xuzhang5788** [mljar/mljar-supervised#373]
After I train my model, I got a new folder. There is a list of several algorithms' results. Is it possible to reuse those trained algorithms?

In addition, if I train my model with an individual algorithm, how to ensemble them together? For example.
First,
automl =AutoML(results_path='rf', algorithms=['Random Forest'], .....)
auroml.fit(X_train, y_train)
Second,
automl =AutoML(results_path='xgbf', algorithms=['Xgboost'], .....)
auroml.fit(X_train, y_train)
Third
automl =AutoML(results_path='cat', algorithms=['Catboost'], .....)
auroml.fit(X_train, y_train)

How to ensemble about three algorithms together?

If I want to try those three algorithms, must I use ?
automl =AutoML(results_path='three algorithms', algorithms=['Random Forest', 'Xgboost', 'Catboost], .....)
auroml.fit(X_train, y_train)

**Comment by pplonski** [comment]
@xuzhang5788 yes, you can reuse models. To use them for computing predictions you need to set path for folder with AutoML models:

```python
automl = AutoML(results_path="AutoML_directory")
automl.predict(X)
```

The `AutoML_directory` is the directory with all models.

If you want to have ensemble from three different algorithms you need to specify them in AutoML constructor:

```python
automl =AutoML(results_path='three algorithms', algorithms=['Random Forest', 'Xgboost', 'Catboost], ...)
auroml.fit(X_train, y_train)
```

**Comment by xuzhang5788** [comment]
Thanks.
Every time, I do automl.fit(X_train, y_train), it takes an amount of time. Sometimes, we use the same algorithms. If we couldn't reuse trained algorithms, it is a kind of waste. Because those trained algorithms have already saved in the directory of AutML_directory. It will be great if somehow can save training time.

**Comment by pplonski** [comment]
@xuzhang5788 yes, it is some waste of resources, but this way code is a little simpler. Maybe in the future, we will add this.
