### ISSUE TITLE
Support for seaborn 0.11.1

### ISSUE THREAD

**Issue by RafaD5** [mljar/mljar-supervised#374]
Hello!

I'm using the Explain mode to do some exploration of the data and to train a simple model. Then I use the trained model to do some error analysis and plot the results but I would like to use the most recent seaborn API.

What I did was go to supervised/eda.py and change all distplot for displot (without the t) and also add the keyword `x` in line 100
```
chart = sns.countplot(
    x=X[col], order=X[col].value_counts().iloc[:10].index, color=BLUE
)
``` 
Now when I use MLJAR with seaborn 0.11.1  I don't get any warnings.

**Comment by pplonski** [comment]
@RafaD5 could you please create PR with update?

**Comment by RafaD5** [comment]
Sure, I'm working on the PR
