### ISSUE TITLE
Setting to More Fully Explore Golden Features?

### ISSUE THREAD

**Issue by strelzoff-erdc** [mljar/mljar-supervised#378]
Hi,

   For a project involving predicting several hierarchal compositional data analysis (CODA) chemical composition labels MLJAR-supervised works very well.  Interestingly the golden features identified mostly have physical interpretation - essentially we are discovering feature combinations that are used in a real life laboratory to distinguish among samples.

So, we have a wish list:
1) can we have a setting to expand the compute budget and number of golden features discovered so we can see if additional known physical properties 'pop up'?
2) Somewhat more complex (and perhapsunreasonable to ask) would be to expand the operations considered in golden feature search, perhaps with this library or other symbolic regression package (https://github.com/MilesCranmer/PySR).  In the current field of study there are many very large public datasets to which this technique could be applied with the aim to discover previously unknown physical relationships among laboratory measures that would provide better real world labeling of samples.

PM me if interested in collaboration

thanks!

**Comment by pplonski** [comment]
Hi @strelzoff-erdc, thank you for adding a feature request. I'm glad that you were able to build good ML models with MLJAR.

1. Right now there is `golden_features` parameter in the `AutoML` constructor that controls if Golden Features will be created or not. I can extend it and use it to specify how many golden features should be added to the dataset. Right now, if Golden Features are created then their number is set to `min(100, max(10, 10% * total number of columns))`

Example proposition:
```
automl = AutoML(golden_features=120)
automl.fit(X, y)
```

It will add 120 golden features to the dataset. Would it work for you?

If `golden_features=True` then the number of golden features will be created with old formula.

What do you mean by expand compute budget for Golden Features? 

2. I can extend operators list or make it customizable. Do you have any specific operators that you would like to use?

3. I'm always happy to help. Not sure what do you mean by collaboration, you can reach me by email piotr at mljar.com

**Comment by pplonski** [comment]
@strelzoff-erdc it is possible to manually set the number of Golden Features. Just set the integer value (desired features count) to `golden_features` parameters in the `AutoML` constructor.

Changes are in the `dev` branch. To install it:
```
pip install -q -U git+https://github.com/mljar/mljar-supervised.git@dev
```
