### ISSUE TITLE
How best to get diversity in final ensemble?

### ISSUE THREAD

**Issue by tmontana** [mljar/mljar-supervised#38]
Hi.  I'm running an experiment with standard XGboost parameters.  In the end I am surprised to see that only 2 models are retained for the ensemble and usually one is significantly more weighted than the other (11 to 1).  What parameters can I change in order to get more models in the ensemble (assuming just XGboost?  So far I have tried 10 initial and 15 initial models as well as 5 hill climbing steps and retain 5 models for improvements but with little difference.  Thanks

**Comment by pplonski** [comment]
Please try:
- more initial models, for example, 20-30, 
- a smaller number of hill-climbing steps: 2 or 3,
- a smaller number of models for improvement in each hill-climbing step, 2 or 3
With such a combination, you should get more diversified models. 

It is also very good to add more data:
- you can try to add new columns by doing simple transformations (subtraction, multiplication) between original columns. You can take a look at my old package for feature generation https://github.com/pplonski/gafe 
- you can try to run different experiments on different subsets of columns and the just average the final models
