### ISSUE TITLE
Problems resuming training

### ISSUE THREAD

**Issue by RafaD5** [mljar/mljar-supervised#382]
Hello!
I was training with mode="Perform" and due to memory usage (#381) the execution of the script was killed. Normally what I do is change model_name to the name of the model just created and the training resumes successfully. But this time I got  the following error for all the models trained in the second session. 
![image](https://user-images.githubusercontent.com/37419841/115329495-0485be80-a158-11eb-80e6-589cf3bafafe.png)
![image](https://user-images.githubusercontent.com/37419841/115329732-575f7600-a158-11eb-9ec3-6027e41a0583.png)
The parameters I used for training were mode="Perform", total_time_limit=60*60*8, max_single_prediction_time=300 and eval_metric = 'mae'
The dataset I'm using do have missing values and I think maybe in the second session of training the preprocessing is not working.

**Comment by pplonski** [comment]
@RafaD5 thank you for reporting! Looks like some problem with code for computing prediction time ...

**Comment by pplonski** [comment]
@RafaD5 problem is fixed now! :) It was a bug. The information about prediction time wasn't saved. After restoring the training this info was missing and cause a crash. Should work now. All changes in the `dev` branch. Thank you!
