### ISSUE TITLE
can not show report when I load the saved model on different directory

### ISSUE THREAD

**Issue by xuzhang5788** [mljar/mljar-supervised#384]
in folder A,
I run 

```python
automl = AutoML(results_path='Morgan_letter_Compete', 
                   mode='Compete', .....)
automl.fit(X_train, y_train)
```

I got a new folder called 'Morgan_letter_Compete'

I moved 'Morgan_letter_Compete' to folder B
then I run 
```python
automl = AutoML(results_path='Morgan_letter_Compete')
automl.report()
```
I got 
```python
TypeError                                 Traceback (most recent call last)
<ipython-input-9-7dfee7d81076> in <module>
----> 1 automl.report()

~/miniconda3/envs/DP/lib/python3.6/site-packages/supervised/automl.py in report(self, width, height)
    375 
    376     def report(self, width=900, height=1200):
--> 377         return self._report(width, height)

~/miniconda3/envs/DP/lib/python3.6/site-packages/supervised/base_automl.py in _report(self, width, height)
   1722         from IPython.display import IFrame
   1723 
-> 1724         main_readme_html = os.path.join(self._results_path, "README.html")
   1725         if not os.path.exists(main_readme_html) or 1:
   1726             fname = os.path.join(self._results_path, "README.md")

~/miniconda3/envs/DP/lib/python3.6/posixpath.py in join(a, *p)
     78     will be discarded.  An empty last part will result in a path that
     79     ends with a separator."""
---> 80     a = os.fspath(a)
     81     sep = _get_sep(a)
     82     path = a

TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by pplonski** [comment]
@xuzhang5788 thank you for reporting, it is a bug! I will fix it.

**Comment by pplonski** [comment]
Fixed. Changes are in the `dev` branch.

**Comment by xuzhang5788** [comment]
Thank you so much. However, I am scared to upgrade it because I have already trained my models using the current version. As you said that if I upgrade it, I can't call back my trained models using the upgraded version and have to retrain my models again. I don't want to take so long to repeat my training process. Anyways, thank you so much for your hard work

**Comment by pplonski** [comment]
There were no breaking changes in save/load. But, to be 100% safe, you can install it in fresh virtualenv and test it from there.

Or just wait for next release, it will have many new features/visualizations.

**Comment by xuzhang5788** [comment]
First of all, I haven't upgraded it yet. Today, I want to analyze the results with a trained model. I trained this model in folder A and I moved the whole results to folder B. In folder B, I did
automl = AutoML(results_path='Morgan_letter_Compete')
automl.predict(X_test) 

However, I got a totally different result. 
After training, I got 

  | MAE | MSE | R2 | pearsonr | spearmanr | CI
-- | -- | -- | -- | -- | -- | --
0 | 0.240736324246594 | 0.162004690231288 | 0.769140499219542 | 0.877221146345892 | 0.862937849550427 | 0.870936454512619

Today I got 

  | MAE | MSE | R2 | pearsonr | spearmanr | CI
-- | -- | -- | -- | -- | -- | --
0 | 1.24688410081038 | 2.40310123722799 | -2.42446105208016 | 0.059867667492714 | 0.064591189962513 | 0.523007540028447

I rechecked the other models that trained in folder B, they are okay.

**Comment by pplonski** [comment]
@xuzhang5788 this might be a bug! I will try to reproduce this with unit tests. Any advices or code examples are welcome!

**Comment by xuzhang5788** [comment]
I didn't move my trained folder, use the same version (this time is dev), training is finished without any error. However, after I restarted my kernel, reloaded my model, and did prediction. I got totally different results, similar to the above results. This is so critical because I couldn't use my trained model for my future prediction. It takes time to train the models. However, you can't trust them because you don't know which one can not perform as you trained.

**Comment by pplonski** [comment]
@xuzhang5788 that issue might be connected with issue #395 - maybe some of the models are not loaded and that's why the bug.

**Comment by pplonski** [comment]
@xuzhang5788 I added a unit test for computing predictions after directory change. The predictions after the dir change are exactly the same as predictions before. This must be some bug that can be reproduced with your code+data. I send you my email, please send me code+data to reproduce the issue and I will fix it.

**Comment by pplonski** [comment]
I'm closing the issue. If you will have similar/other problems please create a new issue.
