### ISSUE TITLE
Feature Request: explicitly provide custom CV-fold indices as argument

### ISSUE THREAD

**Issue by juliuskittler** [mljar/mljar-supervised#394]
I have a feature request regarding the cross validation strategy for the `AutoML` class.

**Current status**

Currently, the parameter `validation_strategy` allows to specify the cross validation strategy as follows (https://supervised.mljar.com/api/):

```shell
{
    "validation_type": "kfold",
    "k_folds": 5,
    "shuffle": True,
    "stratify": True,
    "random_seed": 123
}
```

**Desired feature**

However, it would be very useful to have an alternative option that allows to directly specify the fold indices in the same format as given by `sklearn.model_selection.KFold`, namely as such: `[(tr_indices_fold1, te_indices_fold1), ...., (tr_indices_foldK, te_indices_foldK)]`, where the indices e.g. `tr_indices_fold1` are represented as list or array.

This would be really helpful for cases that require a custom definition of the cross validation folds. For example, this may be necessary for cases where specific observations must not be used as test data points but can be used as training data points.

**Comment by pplonski** [comment]
@juliuskittler thank you for adding an issue. This feature was added recently and is in the `dev` branch, that's why no docs. Details: https://github.com/mljar/mljar-supervised/issues/380

It is implemented as you suggested. The syntax:

```py
automl = AutoML(validation_strategy={"validation_type": "custom"}, ...)
automl.fit(X, y, cv=list_with_indices)
```

To install package from `dev` branch:
```
pip install -q -U git+https://github.com/mljar/mljar-supervised.git@dev
```

@juliuskittler looking for your feedback! :)

**Comment by juliuskittler** [comment]
@pplonski Thank you for your reply. I really appreciate you adding this feature!

Unfortunately, I don't have the option to install from the dev branch currently. But I'm eagerly waiting for your 0.10.4 release :)
