### ISSUE TITLE
Hard coded `n_jobs` during computing importance

### ISSUE THREAD

**Issue by BeZie** [mljar/mljar-supervised#398]
Dear @pplonski ,

I observe significant overload during training despite setting or not setting the n_jobs flag. 

I am not absolutely sure why this happens, but is there a chance that n_jobs is passed both to CV and the algorithms, i.e. doubling the effective number of available cores? 

![error](https://user-images.githubusercontent.com/45383051/118767264-cde9b380-b87d-11eb-941e-598e60efa8cc.png)

**Comment by pplonski** [comment]
@BeZie thank you for reporting, that might be a bug. The `n_jobs` is passed only to algorithms. Could you please provide the code example that you used, so I can try to reproduce the problem.

**Comment by BeZie** [comment]
@pplonski 

In the above example it is essentially,


```
time_limit=3600*4

automl=AutoML(mode="Perform", total_time_limit=3600*48,results_path='Models/{}'.format(target))

X=data.drop('value',1)
y=data['value']

automl.fit(X, y)
```

**Comment by pplonski** [comment]
Thank you, and if you set `n_jobs=1` you will also observe all CPU used?

```py
automl=AutoML(n_jobs=1, mode="Perform", total_time_limit=3600*48,results_path='Models/{}'.format(target))
```

**Comment by BeZie** [comment]
Also in this case, overloading takes place but not for the linear model but during lgbm training. I have stopped the task afterwards, so it might be that other algorithms are affected as well.

Installed version is: lightgbm                  3.0.0                    pypi_0    pypi

**Comment by pplonski** [comment]
@BeZie thank you very much! I fixed the issue. All changes are in the `master` branch. You can install them directly from  GitHub:
```
pip install -q -U git+https://github.com/mljar/mljar-supervised.git@master
```
