### ISSUE TITLE
supervised.exceptions ERROR No models produced

### ISSUE THREAD

**Issue by Bhavani-Shanker** [mljar/mljar-supervised#403]
2021-05-24 18:04:12,100 supervised.exceptions ERROR No models produced. 
Please check your data or submit a Github issue at https://github.com/mljar/mljar-supervised/issues/new.
1_Optuna_LightGBM not trained. Stop training after the first fold. Time needed to train on the first fold 1.0 seconds. The time estimate for training on all folds is larger than total_time_limit.
There was an error during 2_Optuna_Xgboost training.
Please check AutoML_22\errors.md for details.
There was an error during 3_Optuna_CatBoost training.
Please check AutoML_22\errors.md for details.
There was an error during 4_Optuna_NeuralNetwork training.
Please check AutoML_22\errors.md for details.
There was an error during 5_Optuna_RandomForest training.
Please check AutoML_22\errors.md for details.
There was an error during 6_Optuna_ExtraTrees training.
Please check AutoML_22\errors.md for details.
Traceback (most recent call last):

  File "<ipython-input-3-4182f0ec13ac>", line 1, in <module>
    automl.fit(X_train, y_train)

  File "C:\Users\bhava\Anaconda3\envs\py38\lib\site-packages\supervised\automl.py", line 337, in fit
    return self._fit(X, y, sample_weight, cv)

  File "C:\Users\bhava\Anaconda3\envs\py38\lib\site-packages\supervised\base_automl.py", line 1131, in _fit
    raise e

  File "C:\Users\bhava\Anaconda3\envs\py38\lib\site-packages\supervised\base_automl.py", line 1048, in _fit
    raise AutoMLException(

AutoMLException: No models produced. 
Please check your data or submit a Github issue at https://github.com/mljar/mljar-supervised/issues/new.

**Comment by pplonski** [comment]
@Bhavani-Shanker thank you for reporting, please provide the code and data you used, so I can try to reproduce the issue. Thanks!

**Comment by Bhavani-Shanker** [comment]
Hi,
Thanks for your reply.

Here is the code and the data.

#################### Code ##############################################

import pandas as pd
# scikit learn utilites
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
# mljar-supervised package
from supervised.automl import AutoML
import optuna
################################################################################

df = pd.read_excel("Spinach_Farm_Data.xlsx",sheet_name="New_Data_TenPhases_Cumu_Sum",engine='openpyxl')

df.head()

new_df = df[["Rain_0","Rain_1","Rain_2","Rain_3","Rain_4","Rain_5","Rain_6","Rain_7",
             "Rain_8","Rain_9","Temp_Avg_0","Temp_Avg_1","Temp_Avg_2","Temp_Avg_3",
             "Temp_Avg_4","Temp_Avg_5","Temp_Avg_6","Temp_Avg_7","Temp_Avg_8",
             "Temp_Avg_9","Temp_Max_0","Temp_Max_1","Temp_Max_2","Temp_Max_3",
             "Temp_Max_4","Temp_Max_5","Temp_Max_6","Temp_Max_7","Temp_Max_8",
             "Temp_Max_9","Temp_Min_0","Temp_Min_1","Temp_Min_2","Temp_Min_3",
             "Temp_Min_4","Temp_Min_5","Temp_Min_6","Temp_Min_7","Temp_Min_8",
             "Temp_Min_9","RH_0","RH_1","RH_2","RH_3","RH_4","RH_5","RH_6","RH_7",
             "RH_8","RH_9","Soil_Temp_Avg_0","Soil_Temp_Avg_1","Soil_Temp_Avg_2",
             "Soil_Temp_Avg_3","Soil_Temp_Avg_4","Soil_Temp_Avg_5","Soil_Temp_Avg_6",
             "Soil_Temp_Avg_7","Soil_Temp_Avg_8","Soil_Temp_Avg_9","Solar_0","Solar_1",
             "Solar_2","Solar_3","Solar_4","Solar_5","Solar_6","Solar_7","Solar_8",
             "Solar_9","Speed_0","Speed_1","Speed_2","Speed_3","Speed_4","Speed_5",
             "Speed_6","Speed_7","Speed_8","Speed_9","Gust_0","Gust_1","Gust_2","Gust_3",
             "Gust_4","Gust_5","Gust_6","Gust_7","Gust_8","Gust_9","ETO_0","ETO_1",
             "ETO_2","ETO_3","ETO_4","ETO_5","ETO_6","ETO_7","ETO_8","ETO_9",
             "Drill_Week","Harvest_Week","GD","HD/Irr","SL_Farm"]]

X = new_df.drop("SL_Farm",axis=1)
y = new_df["SL_Farm"]


X_train, X_test, y_train, y_test = train_test_split( X, y,stratify=y, test_size=0.20, random_state=42)

automl = AutoML(mode="Optuna", optuna_time_budget=3600)
automl.fit(X_train, y_train)
# automl = AutoML(mode="Compete")

# train models with AutoML
automl = AutoML(mode="Perform")
automl.fit(X_train, y_train)


automl = AutoML(results_path="AutoML_classifier")
automl.fit(X_train, y_train)
automl.fit(X, y)

# compute the accuracy on test data
predictions = automl.predict_all(X_test)
print(predictions.head())
print("Test accuracy:", accuracy_score(y_test, predictions["label"].astype(int)))



Regards
Bhavani



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by pplonski** [comment]
@Bhavani-Shanker thank you for code, could you please attach the data file as well?

**Comment by Bhavani-Shanker** [comment]
It has been attached in my previous email. Please check.

Regards
Bhavani


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by pplonski** [comment]
@Bhavani-Shanker looks like it is not attached by Github notifications. You respond with email to GitHub notifications and the attachment is lost.

Please go directly to tyhe issue page https://github.com/mljar/mljar-supervised/issues/403 and try to attach the file with data.

**Comment by Bhavani-Shanker** [comment]
Here is the file.

Regards

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by pplonski** [comment]
Nope, again, you respond with email to GitHub notification.

Please send me data by email to piotr @ mljar.com

Thanks

**Comment by pplonski** [comment]
hey @Bhavani-Shanker! I've reproduced the bug.

Your data is very imbalanced, there are few samples (less than 20) with classes `4` and `5`. The AutoML detects this and sample up for those classes. But, there is a bug that after the training the `y_train` array contains added samples - it shouldn't. I will fix it.

In the meanwhile, you can just call train/test split before every training:
```py
X_train, X_test, y_train, y_test = train_test_split( X, y,stratify=y, test_size=0.20, random_state=42)
```

You have `random_state` set, so the split will be the same after each call.

**Comment by pplonski** [comment]
@Bhavani-Shanker the problem is fixed, please install the newset code directly from GitHub:

```
pip install -q -U git+https://github.com/mljar/mljar-supervised.git@master
```

Changes will go to version `0.10.5`.
