### ISSUE TITLE
AutoML not accepting 'auto' argument for algorithms parameter

### ISSUE THREAD

**Issue by TerryFoster1721** [mljar/mljar-supervised#406]
In a research study I am a part of, we are attempting to implement AutoML capabilities, and when we try to leave a selection for a list to 'auto' to pass as the algorithms argument in the AutoML call, we get an error that 'auto' is not an accepted algorithm for the task. This happens whether the task is set as auto, binary_classification, multiclass_classification, and/or regression. We are able to use all of the other arguments (Baseline, Linear, etc), without issue, but we would like to use auto to save time in preparing our models (this particular code has the user define the training algorithms with each new model). I have tried using a catch that when the field we are checking to pass to the AutoML call is equal to "auto" that it instead passes a list containing the names of the other algorithms, but for some reason this caused no model to be generated (I assume this is my own fault, that the list was not generated or passed correctly).

Is there any advice for trying to properly implement this type of behavior?

For context, I am using mljar-supervised v 0.10.4, and the area we are trying to get the list of models from is a streamlit multiselect, though I do not believe the select is the issue.

**Comment by pplonski** [comment]
@TerryFoster1721 thank you for reporting, looks like a bug.

You can just don't pass this argument if you want the `auto` mode till I fix this bug (don't pass `algorithms` in the AutoML constructor).

**Comment by pplonski** [comment]
@TerryFoster1721 just checked this issue. All works good, looks like you passed the `auto` in the list. If you want to have an automatic set of algorithms please pass `auto` as a string, example below:

```py
# this should work
# it uses a predefined set of algorithms that depends on AutoML mode
automl = AutoML(algorithms="auto")
automl.fit(X, y)
```
