### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by mrlonely001** [mljar/mljar-supervised#408]
ImportError: cannot import name '_validators' from 'matplotlib.rcsetup' (/usr/local/lib/python3.7/dist-packages/matplotlib/rcsetup.py)

**Comment by mrlonely001** [comment]
> ImportError: cannot import name '_validators' from 'matplotlib.rcsetup' (/usr/local/lib/python3.7/dist-packages/matplotlib/rcsetup.py)

ImportErrorTraceback (most recent call last)
<ipython-input-10-e558a9ea2bf3> in <module>
----> 1 from supervised.automl import AutoML
      2 import lightgbm as lgb
      3 import numpy as np
      4 from sklearn.model_selection import StratifiedKFold
      5 from sklearn.metrics import roc_auc_score, accuracy_score, f1_score, precision_score, recall_score

/usr/local/lib/python3.7/dist-packages/supervised/__init__.py in <module>
      1 __version__ = "0.10.4"
      2 
----> 3 from supervised.automl import AutoML

/usr/local/lib/python3.7/dist-packages/supervised/automl.py in <module>
      1 import logging
      2 
----> 3 from supervised.base_automl import BaseAutoML
      4 
      5 from supervised.utils.config import LOG_LEVEL

/usr/local/lib/python3.7/dist-packages/supervised/base_automl.py in <module>
     19 from sklearn.metrics import r2_score, accuracy_score
     20 
---> 21 from supervised.algorithms.registry import AlgorithmsRegistry
     22 from supervised.algorithms.registry import BINARY_CLASSIFICATION
     23 from supervised.algorithms.registry import MULTICLASS_CLASSIFICATION

/usr/local/lib/python3.7/dist-packages/supervised/algorithms/registry.py in <module>
     68 
     69 # Import algorithm to be registered
---> 70 import supervised.algorithms.random_forest
     71 import supervised.algorithms.xgboost
     72 import supervised.algorithms.decision_tree

/usr/local/lib/python3.7/dist-packages/supervised/algorithms/random_forest.py in <module>
      6 from sklearn.ensemble import RandomForestRegressor
      7 
----> 8 from supervised.algorithms.algorithm import BaseAlgorithm
      9 from supervised.algorithms.sklearn import (
     10     SklearnTreesEnsembleClassifierAlgorithm,

/usr/local/lib/python3.7/dist-packages/supervised/algorithms/algorithm.py in <module>
      1 import uuid
      2 import numpy as np
----> 3 from supervised.utils.importance import PermutationImportance
      4 from supervised.utils.shap import PlotSHAP
      5 from supervised.utils.common import construct_learner_name

/usr/local/lib/python3.7/dist-packages/supervised/utils/importance.py in <module>
      5 import numpy as np
      6 import pandas as pd
----> 7 import matplotlib.pyplot as plt
      8 from sklearn.inspection import permutation_importance
      9 from supervised.algorithms.registry import (

/usr/local/lib/python3.7/dist-packages/matplotlib/pyplot.py in <module>
     34 from cycler import cycler
     35 import matplotlib
---> 36 import matplotlib.colorbar
     37 import matplotlib.image
     38 from matplotlib import _api

/usr/local/lib/python3.7/dist-packages/matplotlib/colorbar.py in <module>
     36 
     37 import matplotlib as mpl
---> 38 from matplotlib import _api, collections, cm, colors, contour, ticker
     39 import matplotlib.artist as martist
     40 import matplotlib.patches as mpatches

/usr/local/lib/python3.7/dist-packages/matplotlib/contour.py in <module>
     15 import matplotlib.colors as mcolors
     16 import matplotlib.collections as mcoll
---> 17 import matplotlib.font_manager as font_manager
     18 import matplotlib.text as text
     19 import matplotlib.cbook as cbook

/usr/local/lib/python3.7/dist-packages/matplotlib/font_manager.py in <module>
     44 from matplotlib.fontconfig_pattern import (
     45     parse_fontconfig_pattern, generate_fontconfig_pattern)
---> 46 from matplotlib.rcsetup import _validators
     47 
     48 _log = logging.getLogger(__name__)

ImportError: cannot import name '_validators' from 'matplotlib.rcsetup' (/usr/local/lib/python3.7/dist-packages/matplotlib/rcsetup.py)

**Comment by pplonski** [comment]
@mrlonely001 thank you for reporting. Could you check the matplotlib version that you are using?

```python
import matplotlib
print(matplotlib.__version__)
```

**Comment by mrlonely001** [comment]
> @mrlonely001 thank you for reporting. Could you check the matplotlib version that you are using?
> 
> ```python
> import matplotlib
> print(matplotlib.__version__)
> ```

3.1.3

**Comment by pplonski** [comment]
Please update your matplotlib package. The requirement for `mljar-supervised` is `matplotlib>=3.2.2`. You can check required packages versions in `requirements.txt` file. The link to file in the repository: https://github.com/mljar/mljar-supervised/blob/2a976e24b495c28b1cabf16bca45bfeb76af1900/requirements.txt#L10


Please try to update matplotlib:
```
pip install -U matplotlib
```

or you can try to update mljar package (the `- U` flag):
```
pip install -U mljar-supervised
```

Please let me know if it works.

**Comment by pplonski** [comment]
@mrlonely001 I'm closing the issue. If you still have problems please reopen the ticket.
