### ISSUE TITLE
Can you add class weights/ sample weights to the search space?

### ISSUE THREAD

**Issue by akiliyiu** [mljar/mljar-supervised#409]

**Comment by pplonski** [comment]
hi @akiliyiu!

The `sample_weight` is supported by MLJAR AutoML. You can pass it as in scikit-learn to the `fit()` method. Please check the docs: https://supervised.mljar.com/api/#supervised.automl.AutoML.fit

The class weights is not implemented yet. The ticket is open https://github.com/mljar/mljar-supervised/issues/155

Please let me know if you need further help.

**Comment by akiliyiu** [comment]
> hi @akiliyiu!
> 
> The `sample_weight` is supported by MLJAR AutoML. You can pass it as in scikit-learn to the `fit()` method. Please check the docs: https://supervised.mljar.com/api/#supervised.automl.AutoML.fit
> 
> The class weights is not implemented yet. The ticket is open #155
> 
> Please let me know if you need further help.

Thank you for your reply. 
Class imbalanced problems can be quite tricky that sometimes I have to run a few trials to search for the optimal class weight. I thought it would save a lot of effort and help with the performance if class weights can be added into search space as well. :)

**Comment by pplonski** [comment]
Do you have any method or package that can be used for weight searching?

**Comment by pplonski** [comment]
I'm closing this issue. The search for class balance weight should be done outside the MLJAR AutoML. This can be easily done by doing some grid search over few balance weight values and training AutoML for each.
