### ISSUE TITLE
Clarification with saving models

### ISSUE THREAD

**Issue by TerryFoster1721** [mljar/mljar-supervised#410]
Currently, according to the documentation, the saving and loading of autoML models is handled automatically, though  according to the documentation this is only the case when attempting to use the model outright. Is there any way already built into the library that would allow us to save information in an easier to read format?

In short, is there a way to save whichever model is deemed the best in a format more in line with how keras is able to save models, with retaining the layers and weights of the models? Or is the documentation simply not updated in such a way where it is clear how to obtain this information without reading through several files within the autoML folders? Are we able to save the models directly, even through use of other libraries, or will calling the load as the documentation specifies allow us to view the details of the model as necessary for something like Transfer Learning?

**Comment by pplonski** [comment]
Models are saved in their internal formats. To have more readable formats then there is a need to write/use same parsers and convertres. I'm not aware of any right now.
