### ISSUE TITLE
Problem with learner_time_limit

### ISSUE THREAD

**Issue by tmontana** [mljar/mljar-supervised#43]
Hi Piotr:

Thanks for the changes made in the ner version.  I'm now getting an error when setting learner_time_limit.  Did you take this option out?  I see in your code that you are setting it automatically as a function of total_time_limit.  Can this be the behavior only if learner_time_limit is None?

**Comment by pplonski** [comment]
Sure, I can keep both. But I will change the name, it will be `model_time_limit`.

Proposed change:
- `total_time_limit` is the time for computing for all models
- `model_time_limit` is the time for computing a single model. A single model can have several learners. For example, when doing cross-validation with 15 folds, then the model will have 15 learners.
- if `model_time_limit` is `None` then its value is computed from `total_time_limit`
- if `total_time_limit` is set and `model_time_limit` is set, then `total_time_limit` constraint will be omitted.

@tmontana what do you think?

**Comment by tmontana** [comment]
Hi Piotr:

This makes sense to me.  Personally I like to set model_time_limit and leave total_time_limit as None.

Thanks,

**Comment by pplonski** [comment]
Done. There are two arguments in `AutoML`: `total_time_limit` and `model_time_limit`.  The behavior is the following:

- `total_time_limit` sets a time limit for all models in `AutoML`
- `model_time_limit` sets a time constraint on one model,
- if both are set, then `model_time_limit` is more important, and `total_time_limit` is not applied.

I've made also changes in `AutoML` constructor. I will create the docs for it (#46).
