### ISSUE TITLE
Error using ML models within Docker

### ISSUE THREAD

**Issue by imalK96** [mljar/mljar-supervised#431]
Hi,
I have a model trained on a Windows machine and everything is working fine but I'm trying to run the model within a Docker container and can't seem to get a prediction by using the same method. The same issue seems to occur on Mac systems too

![Screenshot 2021-07-12 082204](https://user-images.githubusercontent.com/52731064/125224007-54ed6200-e2ea-11eb-9a4a-78ce48e23587.png)

- This is my folder structure and I don't think there is a file path issue as it is working outside of the container (in Windows)

-flask-api
   --app.py
   --Models
   ---Coastal Location Model Production

![Screenshot 2021-07-12 082935](https://user-images.githubusercontent.com/52731064/125225786-7734af00-e2ed-11eb-88fd-baacf53f7ebf.png)

- This is the Dockerfile I'm using

![Screenshot 2021-07-12 082712](https://user-images.githubusercontent.com/52731064/125224341-13a98200-e2eb-11eb-8569-32d1e80f33f9.png)

Any idea what might be causing this?

**Comment by pplonski** [comment]
hi @imalK96, please take a look at the model path, you have `/` and `\` mixed. Looks like the you need to convert `\` to `/` in the `params.json` file and it should work.

You trained models on Widnows machine and the docker is Linux machine, thus a problem.

Please let me know if it works for you.

**Comment by imalK96** [comment]
> hi @imalK96, please take a look at the model path, you have `/` and `\` mixed. Looks like the you need to convert `\` to `/` in the `params.json` file and it should work.
> 
> You trained models on Widnows machine and the docker is Linux machine, thus a problem.
> 
> Please let me know if it works for you.

The problem is I think the mixed ' / ',  ' \ ' are coming from here - Light_GBM framework.json
![Screenshot 2021-07-12 133216](https://user-images.githubusercontent.com/52731064/125252192-b676f600-e315-11eb-8a4f-7c4c14b4a700.png)

This my params.json. How would I enforce the file path to be constructed with / ?

![Screenshot 2021-07-12 133132](https://user-images.githubusercontent.com/52731064/125252290-d3132e00-e315-11eb-81d4-e1cc408d387c.png)

**Comment by pplonski** [comment]
The path construction depends on the operating system that is used. You need to change `\\` to `/` in your `params.json` before running predictions in docker.

**Comment by imalK96** [comment]
Yep, that did the trick. Thanks for all the help :)
