### ISSUE TITLE
Fail to allocate bitmap

### ISSUE THREAD

**Issue by maysen** [mljar/mljar-supervised#432]
Hello!

In the loop, "fail to allocate bitmap" will appear. How to solve this problem.

The package you released is very easy to use

```python
for do in [ i'item1' , 'item2' ]:
     automl = AutoML()
     automl.fit(X, y)

# An error occurred when looping to the second item
```

**Comment by maysen** [comment]
I don't know how to free memory effectively

**Comment by pplonski** [comment]
Do you mean release RAM memory after training? 

I would advise to have separate process for model training. You cant free all memory because packages that are used in AutoML dont release memory properly (lightgbm, catboost and xgboost).

**Comment by maysen** [comment]
> Do you mean release RAM memory after training?
> 
> I would advise to have separate process for model training. You cant free all memory because packages that are used in AutoML dont release memory properly (lightgbm, catboost and xgboost).

ok， think you .
