### ISSUE TITLE
Minimize production

### ISSUE THREAD

**Issue by maysen** [mljar/mljar-supervised#433]
Can I add an option to switch all non model outputs?

For example, when the model is used in the production environment, bitmap and readme are no longer generated. There are only models.

**Comment by pplonski** [comment]
I think you can do this manually, by copying only related models and files. Would it work for you?

**Comment by maysen** [comment]
Thank you for your reply

I want to deploy Automl in a production environment, but when I use the predict() function online, the content of the analysis is rarely used.
