### ISSUE TITLE
Error when using "mae" metric in Optuna mode

### ISSUE THREAD

**Issue by Zacchaeus14** [mljar/mljar-supervised#435]
Hi ,
I encountered the following error when training in optuna mode:
`Exception in LightgbmObjective The entry associated with the validation name "validation" and the metric name "mae" is not found in the evaluation result list [('validation', 'l1', 0.23193058898755722, False)].`
![Screen Shot 2021-07-16 at 17 57 19](https://user-images.githubusercontent.com/64816317/125930040-d6c74707-16b4-43f2-9373-5146c36dfabf.png)
Idk if it's a bug for the metric or I'm feeding bad data. Any help would be great. Thanks!

**Comment by pplonski** [comment]
@Zacchaeus14 looks like some metric bug - thank you for reporting. Do other metrics work without errors? If you remove LightGBM from algorithm list, then other algorithms work as expected for MAE metric?

**Comment by Zacchaeus14** [comment]
> @Zacchaeus14 looks like some metric bug - thank you for reporting. Do other metrics work without errors? If you remove LightGBM from algorithm list, then other algorithms work as expected for MAE metric?

Thank you for reply. The default rmse works. I haven't try removing LightGBM yet.

**Comment by Zacchaeus14** [comment]
@pplonski I think the little bug is here: https://github.com/mljar/mljar-supervised/blob/200b4f36ae4da9df936522644028280b02bf767e/supervised/algorithms/lightgbm.py#L62 
Hopefully, replacing `"mae":"mae"` with `"mae":"l1"` should work.

**Comment by pplonski** [comment]
Thank you @Zacchaeus14!
