### ISSUE TITLE
Add Tabnet algo

### ISSUE THREAD

**Issue by bobcolner** [mljar/mljar-supervised#438]
[TabNet: Attentive Interpretable Tabular Learning](https://arxiv.org/pdf/1908.07442.pdf)

Would be great to add this new deep/attention neural net type to mljar. Performance is competitive with boosted trees and should add diversity to ensembles.

https://github.com/dreamquark-ai/tabnet

**Comment by pplonski** [comment]
@bobcolner have you used TabNet? Does it work good?

Maybe this can be added as the extension to mljar-supervised? (not in the main package, but installed additionally)

**Comment by pangjac** [comment]
Hi @pplonski  I am interested in contributing adding TabNet into mljar-supervised, may I get some thoughts on your comments "as the extension .... installed additionally" ?  what might be an ideal way to add it `"installed additionally"`  ( in my old mind, I am still stuck in the prototype where adding the functionality -> update dependency -> pip install , so I am not sure what would be "installed additionally")  Thanks for the hints and inputs!!

**Comment by pplonski** [comment]
It will be extra package installed by:

```
pip install mljar-supervised[tabnet]
```

**Comment by pplonski** [comment]
I'm closing for now. I don't want to extend required packages, with tabnet it will require pytorch ...
