### ISSUE TITLE
Problem with results_path behavior

### ISSUE THREAD

**Issue by tmontana** [mljar/mljar-supervised#44]
Hi Piotr.  When setting model_path in AutoML definition, if path already exists this generates an error.  System is looking for a .json file which does not exist - unless the model has been fit I assume.  Better behavior might be that if path exists but no .json exists then proceed as if we had just created the directory?

Thanks,

**Comment by pplonski** [comment]
You mean `results_path`. I can add a condition in the code to check if the directory is empty and use it if it is empty.

Initially, I've preferred to not re-use already created directories, because there can be collisions with other files which are produced during AutoML training.

**Comment by tmontana** [comment]
yes results_path - sorry.  So the behavior you are targeting is:

(1) if directory does not exist, create it
(2) if directory exists but empty, use it
(3) if directory exists and contains finished AutoML run then load object into memory
(4) if directory exists, is not empty and does not contain finished AutoML run then generate error

Is that right?

**Comment by pplonski** [comment]
Ok, changes are added to `master` branch. One more thing, if `results_path` is empty, then the directory name will be generated, based on schema: `AutoML_{number}`. The `number` will be tried from 1 to 100 till no directory collision.
