### ISSUE TITLE
Where can I find model details?

### ISSUE THREAD

**Issue by abdulwaheedsoudagar** [mljar/mljar-supervised#447]
I want to see the best model parameters, preprocessing, etc so that I can reproduce it later or train the model again with the same parameters.

Thanks,

**Comment by pplonski** [comment]
During training there is created directory with all results. You can pass the name of the directory in the `results_path` parameter in `AutoML` constructor. If not passed any directory name then a default directory with name `AutoML_*` will be created (the `*` will be the number from 1 to 1000).

In the `results_path`, each model has a directory with all parameters and details. You can open any directory and check `README.md` file for details (metrics, learning curves, ...). Additionally, there is `framework.json` file with all details about preprocessing.
