### ISSUE TITLE
How to use MLJar with big dataset?

### ISSUE THREAD

**Issue by off99555** [mljar/mljar-supervised#449]
Suppose my CSV file is very big like 100 million rows, which cannot be fully contained in memory, how do I use it with MLJar?
This scenario is also quite inevitable if you do data augmentation.

**Comment by pplonski** [comment]
@off99555 right now there is no option to handle such cases. You need to have the full dataset in the memory.

How much memory do you need to store your data?

**Comment by off99555** [comment]
Thanks. My CSV file is like 20GB. I solved it by using a machine with a lot of RAM.
