### ISSUE TITLE
Error for Ensemble

### ISSUE THREAD

**Issue by jmrichardson** [mljar/mljar-supervised#454]
Hi, from errors.md:

Input contains NaN, infinity or a value too large for dtype('float64'). Traceback (most recent call last): File "/home/jmrichardson/anaconda3/envs/tipjar/lib/python3.7/site-packages/supervised/base_automl.py", line 1089, in _fit is_stacked=params["is_stacked"] File "/home/jmrichardson/anaconda3/envs/tipjar/lib/python3.7/site-packages/supervised/base_automl.py", line 394, in ensemble_step self.ensemble.fit(oofs, target, sample_weight) File "/home/jmrichardson/anaconda3/envs/tipjar/lib/python3.7/site-packages/supervised/ensemble.py", line 222, in fit score = self.metric(y, y_ens, sample_weight) File "/home/jmrichardson/anaconda3/envs/tipjar/lib/python3.7/site-packages/supervised/utils/metric.py", line 408, in call return self.metric(y_true, y_predicted, sample_weight=sample_weight) File "/home/jmrichardson/anaconda3/envs/tipjar/lib/python3.7/site-packages/supervised/utils/metric.py", line 25, in logloss ll = log_loss(y_true, y_predicted, sample_weight=sample_weight) File "/home/jmrichardson/anaconda3/envs/tipjar/lib/python3.7/site-packages/sklearn/utils/validation.py", line 63, in inner_f return f(*args, **kwargs) File "/home/jmrichardson/anaconda3/envs/tipjar/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 2229, in log_loss y_pred = check_array(y_pred, ensure_2d=False) File "/home/jmrichardson/anaconda3/envs/tipjar/lib/python3.7/site-packages/sklearn/utils/validation.py", line 63, in inner_f return f(*args, **kwargs) File "/home/jmrichardson/anaconda3/envs/tipjar/lib/python3.7/site-packages/sklearn/utils/validation.py", line 721, in check_array allow_nan=force_all_finite == 'allow-nan') File "/home/jmrichardson/anaconda3/envs/tipjar/lib/python3.7/site-packages/sklearn/utils/validation.py", line 106, in _assert_all_finite msg_dtype if msg_dtype is not None else X.dtype) ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

Please set a GitHub issue with above error message at: https://github.com/mljar/mljar-supervised/issues/new

**Comment by pplonski** [comment]
@jmrichardson can you share a code and data to reproduce the issue?

**Comment by jmrichardson** [comment]
Hi @pplonski ,

Unfortunately, my data set is huge, over 100GB.  However, I haven't been able to reproduce the problem so it may have been an issue with my data prior til now.  I am closing and will let you know if I experience the error again.  Thanks for your help.
