### ISSUE TITLE
pyspark need to be added on requirements.txt

### ISSUE THREAD

**Issue by kmtk49** [mljar/mljar-supervised#464]
my case `pyspark 2.4.4` causes TypeError.
This symptom is fixed when `pyspark 3.1.2` is installed.

there is not noted on requirements.txt. so, I would be revised.
Thanks

**Comment by pplonski** [comment]
@kmtk49 thanks for reporting. The pyspark is not used in MLJAR AutoML. It is dependency that is installed with `dtreeviz` when using conda. Have you used conda? Please take a look at this issue https://github.com/parrt/dtreeviz/issues/144

I hope I will find some time to fix this for them (for dtreeviz conda recipe), or maybe you can help with this?

**Comment by pplonski** [comment]
@kmtk49 I just found that pyspark doesn't work with Python 3.9 - details: https://stackoverflow.com/questions/58700384/how-to-fix-typeerror-an-integer-is-required-got-type-bytes-error-when-tryin

**Comment by kmtk49** [comment]
thank you @pplonski  for quick response. I understand it caused dtreeviz's.
Fortunately issue fixed in my condition, which use conda py388 windows10.
this case might be closed just for me.
