### ISSUE TITLE
Ensemble model only using 2 models to ensemble

### ISSUE THREAD

**Issue by alitirmizi23** [mljar/mljar-supervised#478]
When I look at the readme.md file of the Ensemble folder, it shows only 2 models out of so many others that it used to ensemble. Is there a reason for this? Also, when I look at the Ensemble_stacked, it shows just 1, "Ensemble" model as the one used for stack_ensemble.

**Comment by alitirmizi23** [comment]
Shouldn't it ensemble all trained models?

**Comment by pplonski** [comment]
Ensemble is trying all available models. If models don't improve the performance they are not added to the final ensemble. It is using this [algorithm](http://www.cs.cornell.edu/~alexn/papers/shotgun.icml04.revised.rev2.pdf).

If only one model is selected in ensemble then the ensemble is not selected as the best model.

Two models in the ensemble are fine. In your example 75% of predictions are from `12_CatBoost` and 25% from `4_Default_CatBoost`.

**Comment by alitirmizi23** [comment]
> Ensemble is trying all available models. If models don't improve the performance they are not added to the final ensemble. It is using this [algorithm](http://www.cs.cornell.edu/~alexn/papers/shotgun.icml04.revised.rev2.pdf).
> 
> If only one model is selected in ensemble then the ensemble is not selected as the best model.
> 
> Two models in the ensemble are fine. In your example 75% of predictions are from `12_CatBoost` and 25% from `4_Default_CatBoost`.

Okay that helps. Thanks. Could I also know which stacking/ensemble_stacking algo is being used? I also see only 1 model (Ensemble) in stacking reader.md
