### ISSUE TITLE
Latest version error with 'start_random_models'

### ISSUE THREAD

**Issue by tmontana** [mljar/mljar-supervised#48]
Just got this error during:

automl = AutoML(results_path="mlj_v2_res_1", total_time_limit=360,algorithms=model_types,train_ensemble=True,start_random_models=20,hill_climbing_steps=2,top_models_to_improve=2)

TypeError: __init__() got an unexpected keyword argument 'start_random_models'

**Comment by pplonski** [comment]
Sorry, I've moved `start_random_models` to `set_advanced` method. To set it please call `set_advanced` before calling `fit` method. Example:

```
automl = AutoML()
automl.set_advanced(start_random_models=1)
automl.fit(X, y)
```
