### ISSUE TITLE
X has feature names, but StandardScaler was fitted without feature names

### ISSUE THREAD

**Issue by JacobMarley** [mljar/mljar-supervised#499]
This issue has been coming up when I use, 
automl.predict_proba(input)

I am using the requirements.txt in venv. Shouldn't input have feature names?
This message did not used to come up and I don't know why.

**Comment by pplonski** [comment]
The message might be from a newer version of sklearn. Could you please paste your packages versions? You can try the `pip freeze` command.

**Comment by JacobMarley** [comment]
I think these are the packages in the venv. 

alembic==1.7.5
atomicwrites==1.4.0
attrs==21.2.0
autopage==0.4.0
backcall==0.2.0
catboost==1.0.3
category-encoders==2.3.0
cliff==3.10.0
cmaes==0.8.2
cmd2==2.3.3
colorama==0.4.4
colorlog==6.6.0
colour==0.1.5
cycler==0.11.0
debugpy==1.5.1
decorator==5.1.0
dtreeviz==1.3.2
entrypoints==0.3
fonttools==4.28.3
graphviz==0.19
greenlet==1.1.2
importlib-metadata==4.8.2
iniconfig==1.1.1
ipykernel==6.6.0
ipython==7.30.1
jedi==0.18.1
joblib==1.1.0
jupyter-client==7.1.0
jupyter-core==4.9.1
kiwisolver==1.3.2
lightgbm==3.3.1
llvmlite==0.36.0
Mako==1.1.6
Markdown==3.3.6
MarkupSafe==2.0.1
matplotlib==3.5.0
matplotlib-inline==0.1.3
missingpy==0.2.0
mljar-supervised==0.11.1
nest-asyncio==1.5.4
numba==0.53.0
numpy==1.20.3
optuna==2.10.0
packaging==21.3
pandas==1.3.4
parso==0.8.3
patsy==0.5.2
pbr==5.8.0
pickleshare==0.7.5
Pillow==8.4.0
plotly==5.4.0
pluggy==1.0.0
prettytable==2.4.0
prompt-toolkit==3.0.23
py==1.11.0
pyarrow==6.0.1
Pygments==2.10.0
pyparsing==3.0.6
pyperclip==1.8.2
pyreadline3==3.3
pytest==6.2.5
python-dateutil==2.8.2
pytz==2021.3
pywin32==302
PyYAML==6.0
pyzmq==22.3.0
scikit-learn==1.0.1
scikit-plot==0.3.7
scipy==1.7.3
seaborn==0.11.2
setuptools-scm==6.3.2
shap==0.36.0
six==1.16.0
slicer==0.0.7
SQLAlchemy==1.4.27
statsmodels==0.13.1
stevedore==3.5.0
tabulate==0.8.9
tenacity==8.0.1
threadpoolctl==3.0.0
toml==0.10.2
tomli==1.2.2
tornado==6.1
tqdm==4.62.3
traitlets==5.1.1
wcwidth==0.2.5
wordcloud==1.8.1
xgboost==1.5.1
zipp==3.6.0

**Comment by JacobMarley** [comment]
from requirements.txt
"scikit-learn>=0.24.2"

hmmm. Looks like I have a later version than the requirements despite installing the venv using requirements.txt

**Comment by off99555** [comment]
I also have this issue. It happens when I trained a model with "Neural Network" algorithm.

**Comment by munozariasjm** [comment]
Does the problem continue after running on a new conda environmen?

**Comment by pplonski** [comment]
@munozariasjm it should run without warnings, I've increased minimal `scikit-learn` version to `1.0`.

**Comment by HazelPinto** [comment]
Hi, the same problem is happening again
