### ISSUE TITLE
Update dependencies for Apple Silicon

### ISSUE THREAD

**Issue by mhrmsn** [mljar/mljar-supervised#500]
I've noticed that mljar-supervised currently can't be installed on Apple Silicon devices. This seems to be mainly due to two dependencies:

- shap==0.36.0
  Is there a reason this is fixed to 0.36.0? The requirements further down for shap (numba > llvmlite) can not be satisfied for the ARM devices, but the newer shap version (0.40.0) seems to work fine.
- catboost
  The issue seems to be known and should be fixed soon catboost/catboost#1526

Would be great to have these updated once everything works!

**Comment by pplonski** [comment]
@mhrmsn thank you for checking this! I've subscribed for the catboost issue, when fixed I will update the MLJAR AutoML code. Thanks!

**Comment by genail** [comment]
@pplonski Could it be they've finally fixed it?

**Comment by pplonski** [comment]
Hi @genail,

is it working fine on Apple after packages (`shape` and `catboost`) update?

**Comment by mhrmsn** [comment]
@pplonski I recently tested it, seems to work again! Thanks!
