### ISSUE TITLE
Is it possible to resume in "optuna" mode?

### ISSUE THREAD

**Issue by asdspal** [mljar/mljar-supervised#507]
I'm using Optuna mode to train on regression task. Is it possible to resume the training in Optuna mode? I'm getting error `AutoMLException: Cannot set directory for AutoML. Directory 'AutoML_exp1' is not empty.` .

**Comment by pplonski** [comment]
Hi @asdspal, yes it is possible. You can reuse Optuna hyperparameters that were found in other AutoML training or in unfinished training. You need to pass 'old' parameters in `optuna_init_params` argument. All hyperparameters found during Optuna tuning are saved in the `optuna/optuna.json` file (inside your `results_path` directory).

Example:
```py
optuna_init = json.loads(open('previous_AutoML_training/optuna/optuna.json').read())

automl = AutoML(
    results_path="next_directory_for_AutoML_results",
    mode='Optuna',
    optuna_init_params=optuna_init
)
automl.fit(X, y)
```

Please let me know if it works for you. Good luck!

**Comment by asdspal** [comment]
Thanks, it is working now.
