### ISSUE TITLE
can't find selected features

### ISSUE THREAD

**Issue by prativapokhrel** [mljar/mljar-supervised#509]
I am not being able to find the **selected features** for the best model(example: 52_LightGBM_Selected_Features). The results folder has the dropped features(drop_features.json), but not selected features. Could you please help me with this? 

PS: I am using **Compete** mode

**Comment by pplonski** [comment]
Hi, if you substract dropped features from all features you will get selected features. Please let me know if it works for you.

**Comment by prativapokhrel** [comment]
Hi @pplonski , where can I find all the features because a lot of features(golden features) have been generated while training the models?

**Comment by pplonski** [comment]
Please try to check framework.json file in model directory. There should be listed all features with applied preprocessing. Please let me know if it works for you.

**Comment by prativapokhrel** [comment]
Thank you so much. It helped me, but I found a couple of unknown features being dropped like Dist_Cluster_1, Dist_Cluster_2, Dist_Cluster_4, and Dist_Cluster_5. There was no Dist_Cluster_3 in the dropped features list. Also, I didn't see them in the new columns list.

**Comment by pplonski** [comment]
Great. Those might be features constructed during kmeans feature engineering step.
