### ISSUE TITLE
How are missing values handled?

### ISSUE THREAD

**Issue by nyan314sn** [mljar/mljar-supervised#512]
How are the missing values handled in feature columns ?  Is it always filled with median ?  It would be nice if there is a csv or .md report indicating how missing values are handled for inside each algorithm folder. 

Another issue that is not clear to me pre-processing of data. Does the package handle normalization/standardization etc? What are the main steps the user should do before leveraging the power of this package.

**Comment by pplonski** [comment]
Hi @nyan314sn, it is filled with median and used values are saved in the framework.json file inside each model directory.
