### ISSUE TITLE
Please remove warning messages

### ISSUE THREAD

**Issue by MaciekEO** [mljar/mljar-supervised#514]
File binary_classifier.py was started on Windows 10 using Python 3.8 with Anaconda. AutoML is working good, but there are two recurring errors:
-`'evals_result' argument is deprecated and will be removed in a future release of LightGBM. Pass 'record_evaluation()' callback via 'callbacks' argument instead.`

-`'early_stopping_rounds' argument is deprecated and will be removed in a future release of LightGBM. Pass 'early_stopping()' callback via 'callbacks' argument instead.`

**Comment by pplonski** [comment]
@MaciekEO thanks for reporting assigning to you.
