### ISSUE TITLE
What are the train/test datasets when "validation_type": "split"?

### ISSUE THREAD

**Issue by filipsPL** [mljar/mljar-supervised#519]
Hi,
when the validation strategy is `kfold`, there is a `folds` folder generated with all folds. But where can I find such data for `split` strategy? (i.e., to see what was the training and testing dataset)?

I have the latest version of mljar-supervised  (0.11.1).

best, Filip

**Comment by pplonski** [comment]
Hi @filipsPL, 

looks like there is no such thing logged. Ups ... I've checked and for `kfold` we log indices in numpy format https://github.com/mljar/mljar-supervised/blob/4181299ec5e5e91f57581867fab2c0c97a315cb4/supervised/validation/validator_kfold.py#L101

Would it be ok for you @filipsPL  to log it as numpy files?

**Comment by filipsPL** [comment]
Thanks for super-fast reply.

Yes, numpy format would be perfect!

**Comment by pplonski** [comment]
@MaciekEO please take a look at this issue. Please check:
- how it is saved in `kfold` validation https://github.com/mljar/mljar-supervised/blob/4181299ec5e5e91f57581867fab2c0c97a315cb4/supervised/validation/validator_kfold.py#L101-L102
- it can be added in `split` validation, somewhere here https://github.com/mljar/mljar-supervised/blob/4181299ec5e5e91f57581867fab2c0c97a315cb4/supervised/validation/validator_split.py#L85

**Comment by pplonski** [comment]
Thanks @MaciekEO! @filipsPL the updates are already in the master branch. They will go to the next minor release.

You can install the package with updates:

```
pip install -q -U git+https://github.com/mljar/mljar-supervised.git@master
```

You will find the indices for train and validation in the AutoML results directory. The indices are saved in numpy format. You can read them like:

```py
train_index = np.load(train_index_file)
```

@filipsPL please let us know if it works for you.

**Comment by filipsPL** [comment]
Great, it works! Thank you @pplonski @MaciekEO for quickly addressing the problem.
