### ISSUE TITLE
Option to turn off preprocessing

### ISSUE THREAD

**Issue by twhelan22** [mljar/mljar-supervised#527]
I often work with datasets where preprocessing has already been carried manually, with some categorical columns encoded as ints, date fields already expanded, categorical columns where values are bools or [0, 1], normalization already applied etc. It would be great to be able to turn off preprocessing and still take advantage of the rest of the mljar pipeline.

E.g. something like:
needs_preprocessing=False (default True)
categorical_columns=[LIST OF COLUMNS] (default None)

**Comment by pplonski** [comment]
Hi @twhelan22,

If all your features are ready for analysis (numeric without missing values) then the preprocessing will not be applied. You can check details of applied preprocessing in the `framework.json` file for each model.

(In the case of Neural Networks, you need to assure that feature is scaled.)

**Comment by twhelan22** [comment]
Ah good to know, thanks!
