### ISSUE TITLE
Optuna and Catboost 

### ISSUE THREAD

**Issue by prativapokhrel** [mljar/mljar-supervised#528]
I am trying to train my model in Optuna mode using Catboost and Xgboost. Optuna optimizes Xgboost, but is stuck forever in the case of Catboost. 
![image](https://user-images.githubusercontent.com/20887144/158836605-6cf888e9-e8a9-4396-9f89-96983cfa7891.png)
![image](https://user-images.githubusercontent.com/20887144/158836672-7f79661c-8433-4d7c-a0da-3d4ca7a82e02.png)

It went on for 7 hours straight, only got folds log in the result folder 
![image](https://user-images.githubusercontent.com/20887144/158837030-bcca3b89-7170-46af-a2d5-a0bd7d09f709.png)

Could you please help me with this?

**Comment by pplonski** [comment]
It might be some issue with Catboost itself. Could you please check running Catboost on yor data without AutoML?
