### ISSUE TITLE
A little 🐛 in the printing of XGBoost results

### ISSUE THREAD

**Issue by munozariasjm** [mljar/mljar-supervised#534]
Hi!, 

Just to report a little (and unimportant) bug. When the results of the XGBoost models are printed, I heavily suspect (😂) the rsme and the fitting time are being interchanged:
```6_Xgboost rmse 11.868675 trained in 1264.67 seconds```
Clearly it should be:
```6_Xgboost rmse 1264.67 trained in 11.868675 seconds```
If necessary, tell me, I can open a PR with the fix.
Regards and keep the excellent work on!!!

**Comment by pplonski** [comment]
Hi @munozariasjm,

It should be good. Please check the code: https://github.com/mljar/mljar-supervised/blob/04a90ffbff33b2c93a7c212825b987e73b7f62fe/supervised/base_automl.py#L290-L294

**Comment by pplonski** [comment]
Why do you think that they are interchanged?

**Comment by unreal79** [comment]
There is no bug, I'm sure. munozariasjm doesn't know what he's talking about, it seems.

I'd closed the "issue".

**Comment by munozariasjm** [comment]
Ok, @unreal79. Let's suppose there is absolutely no bug... Then please explain to me how come we can print the RMSE for this toy data obtained by the linear model is:
```3_Linear rmse 0.0 trained in 13.17 seconds```
Here is the [notebook](https://colab.research.google.com/drive/1bLfSuD3PR-UJdkRv4_PzZx2wfkkHLmxt#scrollTo=vNrFRSCrBPVg).

I still don't know where these printing bugs are coming from, but it is not normal.

**Comment by pplonski** [comment]
Thank you @munozariasjm for example code to reproduce the issue. It might be a bug with `get_final_loss()` method. 

Is anyone interested in tracking the bug?

**Comment by Vamp1899** [comment]
@pplonski Not able to understand the error at first place ,can you please elaborate so i can start working on it?
