### ISSUE TITLE
model structure differences between ensemble/stacked/ensemble_stacked

### ISSUE THREAD

**Issue by Tonywhitemin** [mljar/mljar-supervised#544]
Good day!
I am reading your manual now but can't tell the model structure differences between ensemble/stacked/ensemble_stacked...  
![image](https://user-images.githubusercontent.com/88414200/171352890-59abfaf4-355d-4153-9395-5ed3830de862.png)

Following pictures are json files from the example code and the questions are listed below, could you please help to answer them?
1. The meaning of "repeat" here.
2. How can I understand the model structure for these three pictures?
 
ensemble.json
![image](https://user-images.githubusercontent.com/88414200/171356400-39186c8a-f8ac-495a-a99e-3ce0151abebd.png)

Optuna_extratrees_stacked/framework.json
![image](https://user-images.githubusercontent.com/88414200/171358935-0f596639-c8c8-4b89-99d2-27ff67e8bb0d.png)

Ensemble_stacked/ensemble.json
![image](https://user-images.githubusercontent.com/88414200/171359233-0da32cb3-c626-40eb-b31d-63ed993451d5.png)

Best regards

**Comment by Tonywhitemin** [comment]
Hi pplonski
Thanks for your quick reply!

For stack models, I still want to check how will it stack?
For example, following picture shows that it use five model to stack : 
original_LightGBM, original_Xgboost, original_Neural Network, original_Random Forest and original_Extra Trees.

![image](https://user-images.githubusercontent.com/88414200/171525679-12f41184-afac-4e94-a52a-774323af4993.png)
Do they stack sequentially as picture below?
![image](https://user-images.githubusercontent.com/88414200/171526533-4eba2575-4100-442f-a209-b32254744c5b.png)

Another question is about weight, the graph below shows that the sum of weights is  23+21+1+7+1+10+40=103.
Is this normal? (more than 100%). Or am I misunderstanding the rules?
![image](https://user-images.githubusercontent.com/88414200/171524078-041ae7c6-d8fb-4b8f-8fc3-9e8f23ec3df6.png)


So far I just use the sample code to practice this AutoML tool, the result is good to me.
I will use it on the medical dataset when I understand this tool better.
Thanks again for your kindness!

**Comment by pplonski** [comment]
Hi @Tonywhitemin! 

1. In the first picture you selected models that were trained with the Optuna framework.

2. Here is a definition of stacking https://en.wikipedia.org/wiki/Ensemble_learning#Stacking - in MLJAR AutoML the best models are selected and their predictions are added to the original data. Such data is used to train stacked models.

3. In the ensemble there are weights. After summing all predictions in the ensemble they are normalized with the total weight sum. So it can be any total value.

I'm happy to help. Good luck with your data.

**Comment by Tonywhitemin** [comment]
Hi @pplonski ,
Thanks for your help!
As you said, **"in MLJAR AutoML the best models are selected and their predictions are added to the original data. Such data is used to train stacked models."**
So the five models listed below were "the best models" as you mentioned, is that correct?
If above is correct,  what will the final "stacked models" algorithms be? 

https://user-images.githubusercontent.com/88414200/171525679-12f41184-afac-4e94-a52a-774323af4993.png

**Comment by Tonywhitemin** [comment]
Hi @pplonski,
[framework.txt.txt](https://github.com/mljar/mljar-supervised/files/8841681/framework.txt.txt)
Please refer to attachment from the path of "Optuna_extratrees_stacked/framework.json"
If there are some information indicated in this file and I missed, tell me please.
Thanks for your time!

**Comment by pplonski** [comment]
There should be `params.json` or `framework.json` file in the main directory. There should be a separate file with info about golden features as well. Could you send them? Thanks!

**Comment by Tonywhitemin** [comment]
Hi @pplonski 
Following attachment is the params.json file showed as picture below for your reference.
(BTW, in optuna mode, it doesn't have golden_feature.json file in it)
[params.txt.txt](https://github.com/mljar/mljar-supervised/files/8849252/params.txt.txt)

![image](https://user-images.githubusercontent.com/88414200/172272329-89fff542-8dd0-4857-a53c-240fc9cde911.png)

Part of the file infomation showed as below, but still can't understand the structure for the final stacked model...
Could you help with that? Thanks!
![image](https://user-images.githubusercontent.com/88414200/172275535-91e5aa36-48a4-4579-bc5f-75d8475c3491.png)

**Comment by pplonski** [comment]
Here is how the data for stacked models looks like (based on your params):
![image](https://user-images.githubusercontent.com/6959032/172369172-e4623d61-2df6-42b1-b695-b81006fdc234.png)

Original input data plus predictions from previous models are concatenated and form a new input vector.

**Comment by pplonski** [comment]
The stacked can be explainable but it is not implemented in MLJAR AutoML.

I don't understand the second question.

**Comment by Tonywhitemin** [comment]
Sorry for the confusion...
The second question is that , for example:
Following picture is a reference journal from link of: https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0205872
They also used stack model level 1,and they chose support vector machine as the level-1 model algorithm.
Could we know the level-1 stacked model's algorithm in MLJAR-AutoML?
![image](https://user-images.githubusercontent.com/88414200/172569922-b982f216-e6df-41b8-975d-ef3e3c251f78.png)
![image](https://user-images.githubusercontent.com/88414200/172571030-c25ef7bd-5586-44d2-ace5-d8462faa4ebe.png)

**Comment by Tonywhitemin** [comment]
I really appreciate your help, @pplonski !  Now I understand! Thanks for your time!

**Comment by pplonski** [comment]
@Tonywhitemin would you like to help improve MLJAR AutoML docs? The docs are here https://github.com/mljar/docs and are written in Markdown. There might be a separate page about stacking, what do you think? :)

**Comment by Tonywhitemin** [comment]
If you don't mind my English expression, I would like to give it a try! Could you tell me how can I help? :)

**Comment by Tonywhitemin** [comment]
Got it! I will try, thanks!

**Comment by Tonywhitemin** [comment]
Hi @pplonski 
I upload the file to link:
https://github.com/Tonywhitemin/docs
Please help to check if there have any mistake, thanks!

**Comment by pplonski** [comment]
Thank you @Tonywhitemin! The description is good! I have two coding comments:
1. Let's name the file `ensemble-stacking.md`
2. Paths for images should point to directory in the repository. Please update all images to `docs/images/` and use them as 
```
![image description](/docs/images/clip_image002.gif)
``` 
Are you the author of the images?

**Comment by pplonski** [comment]
Thank you @Tonywhitemin!

I've made small fixes in your docs (you can check them here https://github.com/mljar/docs/commit/2ca0391fde8af5ce39ad21ac19a85c8eb9f7ec15)

Your docs is already in the server https://supervised.mljar.com/features/stacking-ensemble/

**Comment by Tonywhitemin** [comment]
I'm glad I can put some effort into this nice tool, thank you so much @pplonski!

**Comment by Tonywhitemin** [comment]
Hi @pplonski 
I read the section of modes at this link: https://supervised.mljar.com/features/modes/
The **"total models tuned for each algorithm"** showed as below image.
![image](https://user-images.githubusercontent.com/88414200/173318976-16200ba9-5a07-4870-ad37-e86db19be642.png)
The numbers here seens reasonable.
But in the section of "**Custom modes"** shows unstacked models number with 10+3*3*2=28...
May I ask why it need to be multiply by 2? 
![image](https://user-images.githubusercontent.com/88414200/173320777-a3aef2c9-5af5-411d-879c-d8ca40afa03f.png)

**Comment by Tonywhitemin** [comment]
Got it! But if base on the calculate method, should the numbers showed below be modified?

![image](https://user-images.githubusercontent.com/88414200/173324062-8639dfc1-1f16-4315-a4d0-e27aa38b9219.png)

**Comment by pplonski** [comment]
You are right! Would you fix this in the docs?

**Comment by Tonywhitemin** [comment]
Hi @pplonski,
I edited the doc and pulled request as below, could you check if it is OK?
Thanks!
![image](https://user-images.githubusercontent.com/88414200/173470403-2def2394-7bdd-495f-a2ed-611cda725ce4.png)
