### ISSUE TITLE
learning_curves chart does not display properly

### ISSUE THREAD

**Issue by tmontana** [mljar/mljar-supervised#55]
The charts for each model are blank.  
See attached.  Thanks

![learning_curves](https://user-images.githubusercontent.com/18288458/79023982-ecad4f00-7b81-11ea-8a9b-356a790b0a9c.png)

**Comment by pplonski** [comment]
It was only 1 iteration, that's why there is no line in the chart. Please run model with a longer time limit.

**Comment by pplonski** [comment]
For learners with 1 iteration I will plot the bar plot. It will be useful for learners which have only 1 iteration, for example Decision Tree or Logistic Regression.

**Comment by tmontana** [comment]
> It was only 1 iteration, that's why there is no line in the chart. Please run model with a longer time limit.

Ah!  makes sense.  I just had trouble imagining that 1 iteration would take 1200 seconds.  Brings me to another point - is there a way we could provide a verbose ++ advanced mode where we could see more details on the training process - maybe a direct feed from the verbose outputs of the underlying models?

**Comment by pplonski** [comment]
I've fixed a problem with no plot for models that have only one iteration.

The example plot for models with one iteration:
![image](https://user-images.githubusercontent.com/6959032/79349706-d8c56c80-7f36-11ea-8a94-4d78be8b2df0.png)

The example plot for models with more than one iteration:
![image](https://user-images.githubusercontent.com/6959032/79349742-ea0e7900-7f36-11ea-9c0d-fe2928ba63b6.png)
