### ISSUE TITLE
Shap values are not produced (parameters norm and vmin/vmax simultaneously is not supported)

### ISSUE THREAD

**Issue by adrienpacifico** [mljar/mljar-supervised#551]
Hi,
Shap dependence plots are not produced anymore by mljar with a lightgbm model.
However, `learner_fold_0_shap_summary.png` and `shap_importance.png` are produced. 

I get the following error message:

```python
Exception while producing SHAP explanations. Passing parameters norm and vmin/vmax simultaneously is not supported. Please pass vmin/vmax directly to the norm when creating it.
Continuing ...
```

The code producing this error looks like the following:

```python 
automl = AutoML(
    mode='Explain',
    stack_models = True,
    algorithms=['LightGBM'],
    eval_metric="auc", 
    golden_features=False,
    total_time_limit=180,
    validation_strategy={"validation_type": "custom"},
    explain_level=2,
)


cv = [(train_indices, validation_indices)]

automl.fit(
    X,
    y,
    sample_weight = df.weight_discounting.values,
    cv=cv
)
```

**Comment by pplonski** [comment]
Thanks for reporting. Does it always happen for LightGBM models? Does it depend on data/validation?

**Comment by adrienpacifico** [comment]
I am not certain. 

1. I am using a docker container that build from a python3 image with no fixed version in my requirements.txt . An I rebuilt it quite often.
2. I am changing my data pre-processing (even though data are largely the same)
3. I just tried to take a subset of the data with very little numerical only feature, and I still have the issue.
4. There is also additional errors/warning that appears in the output:  

```
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf

WARNING:findfont: Font family ['sans-serif'] not found. Falling back to DejaVu Sans.
WARNING:findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial, Liberation Sans, Bitstream Vera Sans, sans-serif
```

**Comment by adrienpacifico** [comment]
Hi,
After some investigations, it seems to come from non-compatibilities between the pinned shap version ( [shap==0.36.0](https://github.com/mljar/mljar-supervised/blob/7a3d2c89007dae159268cc0c7eb3440005fd4f77/requirements.txt#L12)) and the latest version of numpy.

If I unpin the shap version (or if I `pip install shap --upgrade` ) It seems to run smoothly at least for my use case.

@pplonski why did you pin shap?

**Comment by adrienpacifico** [comment]
I am not sure, but it looks ok: https://github.com/adrienpacifico/mljar-supervised/runs/7610955698?check_suite_focus=true

I would have expected that the PR would trigger the CI, it did not right?

**Comment by pplonski** [comment]
@adrienpacifico thanks for PR!
