### ISSUE TITLE
features_selection typo in base_automl.py

### ISSUE THREAD

**Issue by arvkevi** [mljar/mljar-supervised#553]
I'm wondering if there is a typo on [this line](https://github.com/mljar/mljar-supervised/blob/ec309aa731f8dbea029271187ae7d79d18bf44ae/supervised/base_automl.py#L156), should `"features_selectiom"` be changed to `"features_selection"`?

I tried to write a unit test to catch this by fitting AutoML, then manually modifying `params.json`, and loading a new AutoML from file. But I could not get my debugger to step into this line, so figured I'd ask here before going any further. I'm not sure what workflow would trigger this being silently missed, it seems to have little to no impact.

**Comment by Vamp1899** [comment]
Hi , @pplonski i can give it a shot with PR ,but new to open source so might need your guidance a bit.

**Comment by pplonski** [comment]
@Vamp1899 sure! Please follow steps:
- just create a fork
- do a commit with typo fix
- do a PR to mljar-supervised repo

**Comment by pplonski** [comment]
Fixed in #555 

Thank you @arvkevi for finding the bug!
