### ISSUE TITLE
In what situation will cause "Linear algorithm was disabled."

### ISSUE THREAD

**Issue by Tonywhitemin** [mljar/mljar-supervised#554]
Hi @pplonski 
I encountered a problem and hope you can help...
OS: Ubuntu 20.04
problem description: I used explain mode, mission task: binary_classification,and I found that during the process, it showed "Linear algorithm was disabled."
But others algorithm were normal...
Could you help? Thanks!
PS:The dataset is prepared as following.
[test.csv](https://github.com/mljar/mljar-supervised/files/9090899/test.csv)

![image](https://user-images.githubusercontent.com/88414200/178433827-559a73b3-430a-476a-8826-e718df4132ab.png)

**Comment by pplonski** [comment]
Looks like too big a dataset for Logistic Regression. Here is a code:

https://github.com/mljar/mljar-supervised/blob/92706af75bd1859805a413768dc261d0572c3e06/supervised/base_automl.py#L745-L749

Maybe this constraint is too restricted?

**Comment by Tonywhitemin** [comment]
Maybe, since our dataset usually have more than 10k samples...
Could I command out this portion? Will it have other side effect?
By the way, Thanks for your quickly reply as always!

**Comment by pplonski** [comment]
@Tonywhitemin sure you can! No side effects, except the learning, might be long ...

I wish to use [Vowpal Wabbit](https://vowpalwabbit.org/) for linear models :)
