### ISSUE TITLE
final output can be confusing

### ISSUE THREAD

**Issue by tmontana** [mljar/mljar-supervised#56]
This is an example output after all models are done running but there are no column headers to understand what this is.

0 10000000000000.0 0.6530156150511344
1 0.6530156150511344 0.6530156150511344
2 0.6530156150511344 0.6530156151127985
3 0.6530156150511344 0.6529712545924589
4 0.6529712545924589 0.652852026991749
5 0.652852026991749 0.6528075224163983
6 0.6528075224163983 0.6527930299503968

**Comment by pplonski** [comment]
Ups, this some debug output from `Ensemble`. I will remove it.

What do you think about `README.md` for the AutoML experiment and for each model? I'm using VS Code for development, it supports markdown preview, so I can preview reports (with clickable links). I really like them.

**Comment by tmontana** [comment]
Very useful.  The more info the better.  Really like the Readme format.
