### ISSUE TITLE
Ensemble is not picked up though it is the best model

### ISSUE THREAD

**Issue by forustous** [mljar/mljar-supervised#560]
In perform mode, the ensemble is usually the best model. 
However, the ensemble is not selected without reason for the new version 0.11.3.

**Comment by pplonski** [comment]
Why did you close the issue?

**Comment by forustous** [comment]
Because it is not reproduced all the time, however, I can attach a strange example here. The AUCs of ensemble and 27-CatBoost are 0.78905 and 0.775568, respectively, but 27-CatBoost is chosen as the best.
[README.md](https://github.com/mljar/mljar-supervised/files/9398202/README.md)
.

**Comment by pplonski** [comment]
@forustous looks like you are training AutoML in the `Performance` mode. While selecting the best model, AutoML also considers a prediction time on a single sample. You can do two things:
- train on `Compete` mode, to get best performance. Then the prediction time on a single sample is not computed and is not used to select the best model.
- increase the `max_single_prediction_time` to 0.6 seconds (or higher).
