### ISSUE TITLE
Load model in other env

### ISSUE THREAD

**Issue by Garry-wonderwoman** [mljar/mljar-supervised#567]
I am curious to understand how can i shift my model files from one location to another.
1. Is there any way to pickle these files?
2. If I copy entire folder to other env, i have to change path name in every json file
3. is there any way i can shift files for the best model only?

**Comment by pplonski** [comment]
Hi @Garry-wonderwoman!

You need to move the whole folder with all models. You don't need to change anything in json files, just use the new path in the `AutoML` constructor:

```py
automl = AutoML(results_path="new_path_here")
automl.predict(train_data)
```

Currently there is not implemented any solution to select only best model and zip/pickle needed files - sorry! I hope it will be available in the future.

Do you get good models with MLJAR AutoML?

**Comment by Garry-wonderwoman** [comment]
Nopes....if i move my folder to another env....its mandatory for me to keep the folder strucrure intact .....because inside the model files...every model has framework,json which has the path specified in the parent env. It means we cannot port the model from one env to another

**Comment by dcapeluto** [comment]
@Garry-wonderwoman I have trained models in MLJAR in Azure notebooks, and then zipped the entire root folder, downloaded it and placed it elsewhere to run predictions as described by @pplonski. It has to be the root folder with all the models in it (the one that contains the params.json, progress.json, etc), and not each individual model. You can then load the model pointing at that folder. You can use the entire path (e.g. `automl = AutoML(results_path="C:/MLModels/MLJAR")`) and make predictions in any environment, as long as you have the dependencies in that env as well.
