### ISSUE TITLE
Cross validation on imbalanced small dataset causes error

### ISSUE THREAD

**Issue by dracar2s** [mljar/mljar-supervised#569]
Hi. 
I am using a small dataset of 120 rows for binary classification, which is also imbalanced (103:17).
When I use cross validation, the confusion matrix and out-of-folds predictions show that there are 123 datapoints instead of 120.
It seems to think there are 20 cases of the minority class.

I have been able to reproduce this issue with this attached dummy dataset.
Interestingly, if I change the distribution to say, 90:30, this issue doesn't happen.

What do you think is going on?
[dummy.csv](https://github.com/mljar/mljar-supervised/files/9566565/dummy.csv)

**Comment by pplonski** [comment]
Hi @dracar2s!

There is a special function to handle 'drastic` imbalanced datasets:

https://github.com/mljar/mljar-supervised/blob/f591ca1cce4dd06f6dc16d496abd704521bf7891/supervised/base_automl.py#L581-L610

The `3` additional samples were added to have at least `20` samples from each class. Is it ok for you?

Do you get good models with MLJAR AutoML?

**Comment by dracar2s** [comment]
Thanks @pplonski for the real-time response!

I didn't know that function existed.
Unfortunately, I prefer to use only the original data.

Can you tell me how to turn this function off?

If not, would you tell me what the underlying technique is? (like SMOTE?).

I've recently got a breakthrough in classification performance using Optuna mode and am looking forward to use the data to write an academic paper. 
As a novice in coding, I really appreciate the effort you put in to make this package as simple as possible. 

Thank you again!

**Comment by pplonski** [comment]
You can comment off all calls of `_handle_drastic_imbalance` functions in the code ...

The algorithm is very simple. It randomly selects samples (from existing samples of the same class) until it reaches 20 samples for the minor class. You can try to run SMOTE on your data by yourself and then call AutoML. If you have at least 20 samples of each class, then there will be no changes in your dataset.

**Comment by dracar2s** [comment]
So the 3 new samples are copies from 3 of the 17 samples, right?

It would be nice if the function could be toggled. 

In the meantime, I’ll comment out the function. 

Thank you again for the prompt feedback!

**Comment by pplonski** [comment]
> So the 3 new samples are copies from 3 of the 17 samples, right?

Yes.
