### ISSUE TITLE
Error:  ValueError: zero-size array to reduction operation maximum which has no identity

### ISSUE THREAD

**Issue by tmontana** [mljar/mljar-supervised#57]
update:  this works if I increase number of k-folds to be >2.

I've been getting this error after the first model has completed learning:

ValueError: zero-size array to reduction operation maximum which has no identity

```python
automl = AutoML(results_path="mlj_1", tuning_mode='Normal', total_time_limit=None, 
                model_time_limit=30,algorithms=model_types,train_ensemble=False)
automl._validation = {"validation_type": "kfold", "k_folds": 2, "shuffle": False, "stratify": True}

automl.fit(X, y)
```

Error message:

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<timed eval> in <module>

~/anaconda3/envs/mlj_shap_2/lib/python3.6/site-packages/supervised/automl.py in fit(self, X_train, y_train, X_validation, y_validation)
    684                 fout.write(tabulate(ldb.values, ldb.columns, tablefmt="pipe"))
    685         except Exception as e:
--> 686             raise e
    687         finally:
    688             if self._X_train_path is not None:

~/anaconda3/envs/mlj_shap_2/lib/python3.6/site-packages/supervised/automl.py in fit(self, X_train, y_train, X_validation, y_validation)
    643 
    644             for params in generated_params:
--> 645                 self.train_model(params)
    646             # hill climbing
    647             for params in tuner.get_hill_climbing_params(self._models):

~/anaconda3/envs/mlj_shap_2/lib/python3.6/site-packages/supervised/automl.py in train_model(self, params)
    369                 raise AutoMLException(f"Cannot create directory {model_path}")
    370 
--> 371             mf.train()  # {"train": {"X": X, "y": y}})
    372 
    373             mf.save(model_path)

~/anaconda3/envs/mlj_shap_2/lib/python3.6/site-packages/supervised/model_framework.py in train(self)
    156         self.callbacks.on_framework_train_end()
    157         self.train_time = time.time() - start_time
--> 158         self.get_additional_metrics()
    159         logger.debug("ModelFramework end of training")
    160 

~/anaconda3/envs/mlj_shap_2/lib/python3.6/site-packages/supervised/model_framework.py in get_additional_metrics(self)
    233 
    234             self._additional_metrics = AdditionalMetrics.compute(
--> 235                 target, oof_preds, self._ml_task
    236             )
    237             if self._ml_task == BINARY_CLASSIFICATION:

~/anaconda3/envs/mlj_shap_2/lib/python3.6/site-packages/supervised/utils/additional_metrics.py in compute(target, predictions, ml_task)
    169 
    170         if ml_task == BINARY_CLASSIFICATION:
--> 171             return AdditionalMetrics.binary_classification(target, predictions)
    172         elif ml_task == MULTICLASS_CLASSIFICATION:
    173             return AdditionalMetrics.multiclass_classification(target, predictions)

~/anaconda3/envs/mlj_shap_2/lib/python3.6/site-packages/supervised/utils/additional_metrics.py in binary_classification(target, predictions)
     79             },  # there is no threshold for AUC
     80             "f1": {
---> 81                 "score": np.max(details["f1"]),
     82                 "threshold": details["threshold"][np.argmax(details["f1"])],
     83             },

~/anaconda3/envs/mlj_shap_2/lib/python3.6/site-packages/numpy/core/fromnumeric.py in amax(a, axis, out, keepdims, initial)
   2503     """
   2504     return _wrapreduction(a, np.maximum, 'max', axis, None, out, keepdims=keepdims,
-> 2505                           initial=initial)
   2506 
   2507 

~/anaconda3/envs/mlj_shap_2/lib/python3.6/site-packages/numpy/core/fromnumeric.py in _wrapreduction(obj, ufunc, method, axis, dtype, out, **kwargs)
     84                 return reduction(axis=axis, out=out, **passkwargs)
     85 
---> 86     return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
     87 
     88 

ValueError: zero-size array to reduction operation maximum which has no identity
```

Thanks

**Comment by tmontana** [comment]
edit 2:  actually seems to generate this error regardless of k in k-folds

**Comment by pplonski** [comment]
I was trying to reproduce this issue with no success. I was using following command (moving validation parameters to `AutoML` constructor):

```python
automl = AutoML(results_path="mlj_1", tuning_mode='Normal', total_time_limit=None, 
                model_time_limit=30,algorithms=["Random Forest"],train_ensemble=False,
               validation= {"validation_type": "kfold", "k_folds": 2, "shuffle": False, "stratify": True}
               )
automl.fit(X, y)
```

Could you please try to run once again your code with updated package?

**Comment by tmontana** [comment]
Sorry I was not clear in my report.  The problem only occurs with Xgboost.  I can confirm it's still a problem using your code and replacing algo with Xgboost.

Thanks

**Comment by tmontana** [comment]
Gabriel Andraos
www.gsquaredcapital.com<http://www.gsquaredcapital.com>

[cid:f3980226-12de-4786-928e-7c398a996937]

Use by other than intended recipients is prohibited.  This message is provided for information purposes only and should not be construed as an offer to sell or the solicitation of an offer to buy any securities or related financial instruments, as official confirmation of any transaction, or as an official statement of G Squared Capital LLP.  We do not represent that this information is complete or accurate and it should not be relied upon as such.  Before entering into any transaction you should ensure that you independently determine that it is appropriate for you given your objectives, experience, financial resources, and other relevant circumstances and fully understand its potential risks and rewards.  You should consult with your advisors as you deem necessary to make such determinations.  No representation or guarantee is made that any indicative performance or return indicated will be achieved in the future.  All information is subject to change without notice. G Squared Capital LLP is authorised and regulated by the United Kingdom Financial Conduct Authority (Reference Number 739481).

________________________________

**Comment by tmontana** [comment]
![ScreenClip](https://user-images.githubusercontent.com/18288458/79272828-46738900-7ea2-11ea-950f-558bb9816352.png)

**Comment by tmontana** [comment]
automl = AutoML(results_path="mlj_v2_res_real_3_several_trees", tuning_mode='Normal', total_time_limit=None, 
                model_time_limit=20,algorithms=model_types=["Random Forest","Xgboost"] ,train_ensemble=True, validation= {"validation_type": "kfold", "k_folds": 2, "shuffle": False, "stratify": True})

**Comment by pplonski** [comment]
Thank you! I will try to reproduce.

**Comment by pplonski** [comment]
I've run the code with data that you emailed me and all worked. I will try to run it on fresh installation of the package.

![image](https://user-images.githubusercontent.com/6959032/79344410-1672c700-7f30-11ea-81c9-af5fb807bd20.png)

**Comment by pplonski** [comment]
On fresh install:
![image](https://user-images.githubusercontent.com/6959032/79372569-374e1300-7f56-11ea-8108-6f1818a2e801.png)

I will try to set more Xgboost models ...

**Comment by pplonski** [comment]
There was an error when all predictions were constant. It should be fixed now.
