### ISSUE TITLE
Numbers in the confusion matrix doesn't add up to be equal to the size of test data

### ISSUE THREAD

**Issue by haichangsui** [mljar/mljar-supervised#574]
This refers to the binary classification example in the https://github.com/mljar/mljar-supervised#point_right-binary-classification-example

The dataset https://raw.githubusercontent.com/pplonski/datasets-for-start/master/adult/data.csv has 32561 entries. The test data should have 8141 entries (25%).

However, the numbers in the confusion matrix (for example https://github.com/mljar/mljar-examples/blob/master/Income_classification/AutoML_1/5_Default_Xgboost/README.md) adds up to 6512, not 8141.

I manually ran the code in https://github.com/mljar/mljar-supervised#point_right-binary-classification-example and verified that the y_test and prediction were indeed of size 8141. If i manually calculate the confusion matrix, the sum of all the values is correctly 8141:

>>>from sklearn.metrics import *
>>>print(confusion_matrix( y_true=y_test, y_pred=predictions ))
[[5845  380]
 [ 637 1279]]

**Comment by pplonski** [comment]
AutoML in the example is running in the Explain mode. In this mode, there are 75% of data used for training and 25% for validation. 

In the example, you have 32561 of total samples. It is splitted into 24420 training samples and 8141 testing samples.

Training samples are further splitted into train and validation data:
- 75% for training - 18315 samples
- 25% for validation - 6105 samples

Probably you are looking at validation samples.
