### ISSUE TITLE
question about Optuna

### ISSUE THREAD

**Issue by alitirmizi23** [mljar/mljar-supervised#582]
Once again, amazing project and thank you for the work

Could you elaborate on how Optuna mode works? Once it has optimized for a certain eval_metric using 10-fold CV, does it prepare a final model trained on 100% of the data, which will then be loaded once we do .predict()? or will the predictions be average of the 10 models learned during the CV?

**Comment by pplonski** [comment]
It will be the latter, average of 10 models. You can reuse the parameters and train single model. From my experience better results are from average of several models.
