### ISSUE TITLE
change Arial font in base_automl.py to avoid issues in linux

### ISSUE THREAD

**Issue by yairVanti** [mljar/mljar-supervised#590]
in base_automl.py there is the following configuration :
font-family: Arial

it causes ubunto docker containers running mljar to write the following message extensively:

WARNING | matplotlib.font_manager - findfont: Font family 'Arial' not found. 

can this font be changes to some non-office font so this message will disappear ?

**Comment by pplonski** [comment]
Hi @yairVanti,

thanks for reporting, are you able to provide PR? Thanks

**Comment by yairVanti** [comment]
opened https://github.com/mljar/mljar-supervised/pull/593

**Comment by pplonski** [comment]
Fixed in #594 

Thank you @yairVanti

**Comment by yairVanti** [comment]
thanks @pplonski  , can you release a new version with the fix ?

**Comment by pplonski** [comment]
sure!

**Comment by pplonski** [comment]
please see https://github.com/mljar/mljar-supervised/pull/594#issuecomment-1369617264

**Comment by pplonski** [comment]
@Marchlak do we still have problems with font?

**Comment by Marchlak** [comment]
![image](https://github.com/user-attachments/assets/f087e21c-bfbf-4c3c-9097-dca0fe603a74)
I don't have any problems - ubuntu 22.04
