### ISSUE TITLE
Does dtreeviz lib update of API for 2.0 release affect mljar-supervised?

### ISSUE THREAD

**Issue by parrt** [mljar/mljar-supervised#596]
Hi @pplonski, @tlapusan and I are creating a big change to the API for dtreeviz, although we hope it is backwards compatible. Regardless, you will start to get deprecation warnings if you pull in dtreeviz 2.0 (coming out shortly). The current dev branch is the following if you'd like to take a look:

https://github.com/parrt/dtreeviz/tree/dev

Happy to make tweaks to smooth any transitions!  The functionality should be the same.

**Comment by dcapeluto** [comment]
I think this gave me some problems. I had to install the second to last version of mljar-supervised to get it to work. Otherwise `from supervised import AutoML`  throws an error about loading dtreeviz. Just in case someone else faces this, pip3 install mljar-supervised==0.11.3 did the trick for me. As of this comment, the latest version is 0.11.4.

**Comment by parrt** [comment]
Hi @dcapeluto yeah, the only real problem is we need `from dtreeviz import *` vs the old `import dtreeviz` inside mljar.

Confirmed. `from supervised import AutoML` gives:

```
...
  File "/Users/parrt/opt/anaconda3/lib/python3.9/site-packages/supervised/algorithms/decision_tree.py", line 23, in <module>
    from dtreeviz.trees import dtreeviz
ImportError: cannot import name 'dtreeviz' from 'dtreeviz.trees' (/Users/parrt/opt/anaconda3/lib/python3.9/site-packages/dtreeviz-2.0.0-py3.9.egg/dtreeviz/trees.py)
```

**Comment by dcapeluto** [comment]
I think I also pip installed a version of dtreeviz <2.0 for this to work. Note: installing dtreeviz to <2.0 with version 0.11.4 of mljar didn't work for me. I had to installed a lower version of both.

**Comment by GuidoBartoli** [comment]
I confirm this issue with Jupyter-Lab 3.5.2, using `from supervised.automl import AutoML` produces the following error:

```ImportError: cannot import name 'dtreeviz' from 'dtreeviz.trees'```

Forcing installation of previous version with `dtreeviz==1.4.1` temporarily solves this issue.

**Comment by tlapusan** [comment]
Hi everyone,

the import "from dtreeviz.trees import dtreeviz" is not anymore supported in version 2.0. We moved the dtreeviz() function for trees.py module into another module. I guess it's our backward compatibility issue here.

To still have access to the dtreeviz() function in the 2.0, you will only need the "from dtreeviz import *"

Hope that this will solve the issue.

**Comment by pplonski** [comment]
Thank you @parrt and @tlapusan for the update. The `dreeviz` is amazing, I wish there was an interactive version for Jupyter Notebook.

I've changed the import in the code and released the new version `0.11.5`.

**Comment by pplonski** [comment]
Thank you @parrt and @tlapusan for the update. The `dreeviz` is amazing, I wish there was an interactive version for Jupyter Notebook.

I've changed the import in the code and released the new version `0.11.5`.

**Comment by tlapusan** [comment]
thanks @pplonski, glad that the issue is solved. Curious what do you mean by interactive version ? :)

**Comment by pplonski** [comment]
I mean visualization where you can fold/unfold nodes in the tree and check paths through the tree for selected sample.
