### ISSUE TITLE
ERROR:supervised.exceptions:No models produced. 

### ISSUE THREAD

**Issue by moonjoo98** [mljar/mljar-supervised#597]
I have done the installation in various ways at Google Cop, but all of them show the following results.
help me plaese..

ERROR:supervised.exceptions:No models produced. 
Please check your data or submit a Github issue at https://github.com/mljar/mljar-supervised/issues/new.
AutoML directory: AutoML_3
The task is multiclass_classification with evaluation metric logloss
AutoML will use algorithms: ['Baseline', 'Linear', 'Decision Tree', 'Random Forest', 'Xgboost', 'Neural Network']
AutoML will ensemble available models
AutoML steps: ['simple_algorithms', 'default_algorithms', 'ensemble']
'Baseline' Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/supervised/tuner/mljar_tuner.py", line 195, in generate_params
    return self.simple_algorithms_params(models_cnt)
  File "/usr/local/lib/python3.8/dist-packages/supervised/tuner/mljar_tuner.py", line 382, in simple_algorithms_params
    params = self._get_model_params(model_type, seed=i + 1)
  File "/usr/local/lib/python3.8/dist-packages/supervised/tuner/mljar_tuner.py", line 954, in _get_model_params
    model_info = AlgorithmsRegistry.registry[self._ml_task][model_type]
KeyError: 'Baseline'

Skip simple_algorithms because no parameters were generated.
'Xgboost' Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/supervised/tuner/mljar_tuner.py", line 197, in generate_params
    return self.default_params(models_cnt)
  File "/usr/local/lib/python3.8/dist-packages/supervised/tuner/mljar_tuner.py", line 431, in default_params
    if self.skip_if_rows_cols_limit(model_type):
  File "/usr/local/lib/python3.8/dist-packages/supervised/tuner/mljar_tuner.py", line 400, in skip_if_rows_cols_limit
    max_rows_limit = AlgorithmsRegistry.get_max_rows_limit(
  File "/usr/local/lib/python3.8/dist-packages/supervised/algorithms/registry.py", line 51, in get_max_rows_limit
    return AlgorithmsRegistry.registry[ml_task][algorithm_name]["additional"][
KeyError: 'Xgboost'

Skip default_algorithms because no parameters were generated.
---------------------------------------------------------------------------
AutoMLException                           Traceback (most recent call last)
[<ipython-input-96-165847d73b57>](https://localhost:8080/#) in <module>
----> 1 automl.fit(X, y)

2 frames
[/usr/local/lib/python3.8/dist-packages/supervised/base_automl.py](https://localhost:8080/#) in _fit(self, X, y, sample_weight, cv)
   1049                 if "hill_climbing" in step or step in ["ensemble", "stack"]:
   1050                     if len(self._models) == 0:
-> 1051                         raise AutoMLException(
   1052                             "No models produced. \nPlease check your data or"
   1053                             " submit a Github issue at https://github.com/mljar/mljar-supervised/issues/new."

AutoMLException: No models produced. 
Please check your data or submit a Github issue at https://github.com/mljar/mljar-supervised/issues/new.

**Comment by pplonski** [comment]
Hi @moonjoo98, how large is your data? Maybe the time-limit is too low for your data size.

**Comment by moonjoo98** [comment]
답변해줘서 감사합니다 @pplonski 
나는 멀티라벨(3)  262 x 20의 트레인 데이터 셋으로 학습을 진행하고 있다. 공모전을 진행중이여서 옵션도 compete로 설정해 놨는데 혹시 데이터가 너무 적어서 문제가 생기는 것일까

**Comment by pplonski** [comment]
MLJAR AutoML can work with binary classification or mutli-class classification, mutli-label is not supported.

**Comment by moonjoo98** [comment]
Oh, sorry. The classes I want to predict are 'A', 'B', and 'C'. Wouldn't it be supported in this case?

**Comment by pplonski** [comment]
If only one of the classes can be selected for one sample, then it is supported. 

Please provide code and data to reproduce the issue.
