### ISSUE TITLE
Add option to not shuffle rows

### ISSUE THREAD

**Issue by tmontana** [mljar/mljar-supervised#6]
When dealing with time series data it is important to not shuffle rows when performing cross-validation.  Would be good to have that as an option.

**Comment by pplonski** [comment]
Right now, as default the 5-fold cross-validation is used for assesing model's performance. To change this behavior we need to add validation variable to AutoML interface.

**Comment by pplonski** [comment]
This can be done by setting the `_validation` variable after `AutoML` object is constructed. Example:

```
automl = AutoML()
automl._validation = {"validation_type": "kfold", "k_folds": 5, "shuffle": False}
automl.fit(X, y)  
```
