### ISSUE TITLE
Can I install mljar-supervised on m1 mac?

### ISSUE THREAD

**Issue by maegnji** [mljar/mljar-supervised#603]
pip install mljar-supervised
error on m1 mac!

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

Building graph of deps:   0%|          | 0/5 [00:00<?, ?it/s]
Examining mljar-supervised:   0%|          | 0/5 [00:00<?, ?it/s]
Examining @/osx-arm64::__unix==0=0:  20%|██        | 1/5 [00:00<00:01,  2.46it/s]
Examining @/osx-arm64::__unix==0=0:  40%|████      | 2/5 [00:00<00:00,  4.91it/s]
Examining @/osx-arm64::__archspec==1=arm64:  40%|████      | 2/5 [00:00<00:00,  4.91it/s]
Examining @/osx-arm64::__osx==13.0.1=0:  60%|██████    | 3/5 [00:00<00:00,  4.91it/s]    
Examining python=3.10:  80%|████████  | 4/5 [00:00<00:00,  4.91it/s]                 
                                                                    

Determining conflicts:   0%|          | 0/5 [00:00<?, ?it/s]
Examining conflict for mljar-supervised python:   0%|          | 0/5 [00:00<?, ?it/s]
                                                                                     
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

**Comment by pplonski** [comment]
Thanks for reporting. Do you have an idea what can be broken?

**Comment by maegnji** [comment]
successfully installed!
i installed wordcloud, shap, lightgbm each

**Comment by maegnji** [comment]
yes. It didn't work "pip install" in wordcloud, shap, lightgbm
so, I install those packages manually.
