### ISSUE TITLE
RandomForest Criterion Error

### ISSUE THREAD

**Issue by Le2Seungyoon** [mljar/mljar-supervised#604]
Hello, I have question for running Random Forest and Extra Trees in AutoML.
Random Forest and Extra Tree got same error, which is: 
The 'criterion' parameter of RandomForestRegressor must be a str among {'squared_error', 'poisson', 'absolute_error', 'friedman_mse'}. Got 'mse' instead.
But actually, I set my metric to mae.
How can I fix this error?
![스크린샷 2023-01-19 오전 10 06 45](https://user-images.githubusercontent.com/118061818/213331698-a5d07fd7-24d6-473f-9ea4-d1484f5a879c.png)
![스크린샷 2023-01-19 오전 10 07 21](https://user-images.githubusercontent.com/118061818/213331811-c81654ac-f3e9-436c-b203-888b1f33fc9b.png)

**Comment by pplonski** [comment]
Hi @Le2Seungyoon, please update sklearn and mljar-supervised to the latest versions.

There was an update in the latest sklearn and mae is no longer supported.

**Comment by Le2Seungyoon** [comment]
Thank you for advice!
After adding bagging models to Ensemble Stacked, my score improved!
![스크린샷 2023-01-20 오전 9 04 36](https://user-images.githubusercontent.com/118061818/213589115-5cb81683-9d31-4f7a-acfa-bc904ec9af6b.png)
