### ISSUE TITLE
Dtreeviz requirement is too large

### ISSUE THREAD

**Issue by drskd** [mljar/mljar-supervised#605]
Hi,

Thanks for the great package! I really like to use it and it's now my go-to-move to fit a model when I want to have a quick overview of the performance I can achieve on a dataset before moving to specific adaptations for my use case, if I need any.

I noticed that dtreeviz recently released a new version (2.0+) and one of the mljar import statement does not hold anymore:

> File "/lib/python3.8/site-packages/supervised/algorithms/decision_tree.py", line 23, in module
`from dtreeviz.trees import dtreeviz`

> ImportError: cannot import name 'dtreeviz' from 'dtreeviz.trees' 

I guess the easiest and quickest way would be to bound the dtreeviz version to <=1.4.1 in the requirements, and keep the adaptation for the upgrade to dtreeviz 2.0+ version for later.

Thanks again, and keep up the great work !

**Comment by pplonski** [comment]
Hi @drskd, thanks for kind words! Please try to upgrade mljar-supervised to the latest version, it should be fixed.

Anyway I think it might be good to have conditional import depending on dtreeviz package version.
