### ISSUE TITLE
Provided docker example crashes on "Basic usage" script due to missing fonts

### ISSUE THREAD

**Issue by elmccd** [mljar/mljar-supervised#606]
Running Dockerfile and Python script provided on https://supervised.mljar.com/ crashes due to missing fonts (?): 

![screenshot_101](https://user-images.githubusercontent.com/2963340/215352310-26b193b6-6caa-4f70-b27b-64f5ac64139b.png)

I managed to get around it by changing base python image to:
```
FROM python:3.7
```

Probably could be fixed better.

**Comment by yairVanti** [comment]
this issue arise because of lacking in fonts in the installed machine.
you can install it on the docker with :

RUN apt-get update && \
    apt-get install -y wget \
    fontconfig && \
    wget http://ftp.br.debian.org/debian/pool/contrib/m/msttcorefonts/ttf-mscorefonts-installer_3.6_all.deb && \
    apt --fix-broken install -y ./ttf-mscorefonts-installer_3.6_all.deb && \
    rm ttf-mscorefonts-installer_3.6_all.deb && \
    fc-cache -f -v
    
  worked for me with:
  FROM python:3.9.16-slim-bullseye
