### ISSUE TITLE
improving versions of numba

### ISSUE THREAD

**Issue by adrianblazeusz** [mljar/mljar-supervised#615]
The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.

**Comment by pplonski** [comment]
I filtered out Numba warnings. All warnings are from `shap` package and we are all waiting for `shap` new release https://github.com/slundberg/shap/issues/2979
