### ISSUE TITLE
Problems deploying models dataset

### ISSUE THREAD

**Issue by Selphie14100** [mljar/mljar-supervised#623]
Assume I have a simple model with inputs A B C,
I want to AutoML to predict from a dataframe.  Which of the following can it do?
A dataframe unlabelled with columns for A B and C
A dataframe marked with columns A B C
A dataframe marked with columns C D A E B

**Comment by pplonski** [comment]
Sorry @Selphie14100 - I dont understand the question ... Could you please add more details?

You can use trained ML models to predict target values for new data.

**Comment by Selphie14100** [comment]
Sorry if I want to use my model on on some new data, does the new data have to be column labelled(I assume Yes :-) ), If it is column labelled do the columns have to be in the same order?
Can the supplied data have extra columns in it that the model just ignores?
Reason is I have multiple models to run on similar but not identical datasets. So loading the one dataset with all the needed columns is easier than having multiple datasets with only the variables that a given model uses.

**Comment by pplonski** [comment]
- yes, you need to provide feature names for your data (you need column labels),
- AutoML will use only features that were used during the training - you can have new features and different order in your new data.

**Comment by Selphie14100** [comment]
well that was easy ! thank you.
