### ISSUE TITLE
Not able to take full time to train the model 

### ISSUE THREAD

**Issue by HazelPinto** [mljar/mljar-supervised#624]
Sorry if this sounds basic but,
I have the following code: 
automl = AutoML(mode="Perform", results_path='/home/erik002/DatosZ/modelo9a',
                total_time_limit=26*3600)
automl.fit(X_train, y)

where I intend to give the algorithm 26 hours to train the models so I can have a good one 
The issue is that it just takes only about 6 hours to complete the task and make the models (it trains them very bad) 

With the same data on AutoWeka and 24 hours of full training I get way better performance  

Is there any way to take all the hours I'm indicating in order to train a better model?

**Comment by pplonski** [comment]
Hi @HazelPinto, 
Have you tried to set `mode="Compete"`? Please let me know if it helps.
