### ISSUE TITLE
Doubt regarding -> pipeline = make_pipeline(RandomOverSampler(), AutoML())

### ISSUE THREAD

**Issue by puneeshkhanna** [mljar/mljar-supervised#627]
Hi ,

If I build a pipeline like above for an imbalanced dataset, then during the CV folds of AutoML - is there a chance of data leakage between train and validation sets of the CVs because the minority class samples will be over sampled by over sampler and then in AutoML , CV folds will be created so sample sample of minority class may exist in train and validation CV ?

**Comment by pplonski** [comment]
If you have multiple samples that are identical then they can be distributed into train and validation sets. You can provide custom indices for train and validation sets if you would like to prevent this.

**Comment by puneeshkhanna** [comment]
Any pointer for it. I m using mode=compete which is further doing 10 fold CV.

**Comment by pplonski** [comment]
Please take look at this comment https://github.com/mljar/mljar-supervised/issues/401#issuecomment-852909390
