### ISSUE TITLE
Doubt - Does mljar autoML also take care of applying RandomScaler, minmaxScaler etc?

### ISSUE THREAD

**Issue by puneeshkhanna** [mljar/mljar-supervised#628]
Also will the model perform better then if we feed in the scaled data to the  AutoML pipeline ?

**Comment by pplonski** [comment]
There shouldn't be any difference. AutoML can perform data scaling if needed.

**Comment by puneeshkhanna** [comment]
@pplonski  - thanks for the quick replies. I m already trying mljar autoML on a kaggle running competition dataset with mode=compete and seeing exciting results. Is data scaling information revealed somewhere in the logs etc. Will try to figure out too.
