### ISSUE TITLE
Installing error

### ISSUE THREAD

**Issue by ConnyGarcia** [mljar/mljar-supervised#633]
I have tried with pip, conda and clonning and I still have the same error

ImportError: DLL load failed while importing _imaging: The specified module could not be found.

I also tried with the right spicy and sklearn and nothing

**Comment by pplonski** [comment]
What python version are you using? Could you please provide full output log?

**Comment by pplonski** [comment]
Hi @ConnyGarcia,

Could you please try installation with Python version 3.9.
