### ISSUE TITLE
Error: Algorithm should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'

### ISSUE THREAD

**Issue by yiannis-gkoufas** [mljar/mljar-supervised#638]
Hi!

Recently I started getting this error (or warning?) with binary classification.
Minimal code to reproduce the problem:

```
from supervised import AutoML

if __name__ == '__main__':
    from sklearn.datasets import make_classification
    X, y = make_classification(n_samples=100000, n_features=20, n_redundant=2)
    from sklearn.model_selection import train_test_split
    X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.3)
    automl = AutoML(eval_metric="accuracy")
    automl.fit(X_train, y_train)
    automl.report()
```
I get multiple messages:
```
DecisionTreeAlgorithm should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.
Problem during computing permutation importance. Skipping ...
```

Is it a new bug or we can just ignore it?
Thank you!

**Comment by pplonski** [comment]
Hi @yiannis-gkoufas,

Thank you for reporting the issue and thanks for code to reproduce the issue. I need to look closer into it. Hard to say is it bug or can be ignored. Any help will be appreciated :)

**Comment by yiannis-gkoufas** [comment]
Sounds like an update of sklearn might have caused it?

**Comment by pplonski** [comment]
I'm not sleeping - fixing ... Looks like after `sklearn` update the warning started to popup. To fix it I've added `ClassifierMixin` or `RegressorMixin` from `sklearn.base` for each algorithm.

I've seen few more warnings, I would like to fix them and then release a new version.
