### ISSUE TITLE
AutoML with Fairness mitigation fails with two sensitive features for regression use cases

### ISSUE THREAD

**Issue by KarthikDutt** [mljar/mljar-supervised#641]
No models are produced when two sensitive features are passed with the target as a continuous variable. The process fails with the error: 

To reproduce the issue, please select the attributes 'race' and 'Age' and the target variable as 'Fnlwgt' in the adult income dataset. 

```
  File "C:\Users\kar11081\AppData\Local\ESRI\conda\envs\dl-env\lib\site-packages\supervised\automl.py", line 409, in fit
    return self._fit(X, y, sample_weight, cv, sensitive_features)
  File "C:\Users\kar11081\AppData\Local\ESRI\conda\envs\dl-env\lib\site-packages\supervised\base_automl.py", line 1272, in _fit
    raise e
  File "C:\Users\kar11081\AppData\Local\ESRI\conda\envs\dl-env\lib\site-packages\supervised\base_automl.py", line 1162, in _fit
    raise AutoMLException(
supervised.exceptions.AutoMLException: No models produced. 
Please check your data or submit a Github issue at https://github.com/mljar/mljar-supervised/issues/new.
```

On debugging, it looks like the weights are inf for certain combinations in optimization.py which causes the process to stop. 

`w = target.shape[0] / len(sensitive_indices) / np.sum(indices)`

**Comment by pplonski** [comment]
Hi @KarthikDutt,

Thank you for reporting the issue. Looks like a bug. Are you able to provide unit test case to reproduce the issue?

**Comment by KarthikDutt** [comment]
Hi @pplonski , THanks for looking into it. Will send it in a day or two.

**Comment by KarthikDutt** [comment]
You can use this test case to reproduce the issue: 

X = np.random.uniform(size=(30, 2))
y = np.random.randint(0, 100, size=(30,))
S = pd.DataFrame({"sensitive": ["White", "Black"] * 15,"sensitive2": ["Male", "Female"] * 15})

automl = AutoML(
    results_path=<path>,
    model_time_limit=10,
    algorithms=["Xgboost"],
    explain_level=0,
    train_ensemble=False,
    stack_models=False,
    start_random_models=1,
)

automl.fit(X, y, sensitive_features=S)

**Comment by KarthikDutt** [comment]
Hi @pplonski  - Did you get a chance to look at this?

**Comment by pplonski** [comment]
Hi @KarthikDutt,

Sorry, I was at EuroSciPy conference last week, and now working on new projects ... Hard to estimate when I will have time to look into it ...

**Comment by aplonska** [comment]
Hi @KarthikDutt, we have allocated time next week to address and resolve this issue.

**Comment by KarthikDutt** [comment]
@pplonski @aplonska - Thanks for the update.

**Comment by pplonski** [comment]
Hi @KarthikDutt, @aplonska - I confirm that I can reproduce the issue. Working on a fix.
