### ISSUE TITLE
[ENHANCEMENT] Report does not say if the model is fair for Regression use cases 

### ISSUE THREAD

**Issue by KarthikDutt** [mljar/mljar-supervised#642]
For classification problems, the report gives the following statement indicating if the model is fair or not. However, the same is not printed for regression. It will be good if a similar statement is there in the regression reports. 

![MicrosoftTeams-image (7)](https://github.com/mljar/mljar-supervised/assets/22084416/9a19af98-408d-4baa-aad5-612a018bb597)

**Comment by pplonski** [comment]
You are right, it should be added for regression as well. It should be done in file https://github.com/mljar/mljar-supervised/blob/master/supervised/fairness/report.py

**Comment by pplonski** [comment]
@aplonska, @KarthikDutt - working on this right now.

**Comment by pplonski** [comment]
I've added information about model fairness for regression tasks. Example, sentence for fair model:

```
Model is fair for sensitive_1 feature. The Group Loss Ratio @ RMSE value is above threshold 0.8.
```
