### ISSUE TITLE
Xgboost : AttributeError: 'Booster' object has no attribute 'best_ntree_limit' 

### ISSUE THREAD

**Issue by adrienpacifico** [mljar/mljar-supervised#649]
On a fresh install of MLJar, I get the following error when launching `automl.predict`.

Xgboost has introduced a version 2.0, 11 hours ago on Pipy.

**Comment by yamenw** [comment]
I am also experiencing the same issue on a fresh install, the other classifiers are working as expected, but Xgboost writes this error to `error.md`:

```
'Booster' object has no attribute 'best_ntree_limit' Traceback (most recent call last): File "C:\Users\user\anaconda3\lib\site-packages\supervised\base_automl.py", line 1195, in _fit trained = self.train_model(params) File "C:\Users\user\anaconda3\lib\site-packages\supervised\base_automl.py", line 401, in train_model mf.train(results_path, model_subpath) File "C:\Users\user\anaconda3\lib\site-packages\supervised\model_framework.py", line 254, in train learner.fit( File "C:\Users\user\anaconda3\lib\site-packages\supervised\algorithms\xgboost.py", line 247, in fit self.best_ntree_limit = self.model.best_ntree_limit AttributeError: 'Booster' object has no attribute 'best_ntree_limit'
```

This is on Windows + Anaconda + Python 3.10.9 + AutoML version 1.0.2

**Comment by adrienpacifico** [comment]
@yamenw
`pip install xgboost==1.7.6` will probably solve the issue.

**Comment by yamenw** [comment]
@adrienpacifico That fixed the problem for me, thanks a lot!

**Comment by pplonski** [comment]
I've fixed the issue. MLJAR AutoML will use Xgboost in version > 2.0.0. The new release should be soon :+1:
