### ISSUE TITLE
How to programmatically get algorithm/best model (Xgboost) result files and feature importance list

### ISSUE THREAD

**Issue by ashleyabraham** [mljar/mljar-supervised#656]
I am looking at the code and API/documentation to programmatically get the best model's result files , such as `#_Default_Xgboost/learner_fold_0_shap_importance.csv` without hard coding the file path, is it possible to do so with the current API?

**Comment by ashleyabraham** [comment]
Appreciate the help, Is there a way to get the feature importance list programmatically that is written to the csv file?

**Comment by pplonski** [comment]
No, you need to manually load it from csv file.
