### ISSUE TITLE
fit a model using mapie regressor 

### ISSUE THREAD

**Issue by sraghavan0610** [mljar/mljar-supervised#660]
Hi I am trying to use a mapie regressor on top of a trained xgboost model trained using mljar.
This is what I am doing 
```
automl = AutoML(results_path ="AutoML_1) # this will load the best performing model which is xgboost
mapie_re = MapieRegressor(automl, cv=10, random_state=2)
mapie_re.fit(x_train, y_train) 
mapie.predict(x_test)
 
```
This approach seems to not work so I would like to save the original best performing model as a .pkl or .joblib file. Please advice! 

Thanks

**Comment by pplonski** [comment]
What is the error from `MapieRegressor` when using AutoML? The good approach might be to use AutoML to find good hyperparameters set and then create model manually which can be used with `MapieRegressor`.
