### ISSUE TITLE
Typo in Decision Tree model selector

### ISSUE THREAD

**Issue by molspace** [mljar/mljar-supervised#663]
https://github.com/mljar/mljar-supervised/blob/08d5e6adcb622d29639e5906e7a174537f32f5f2/supervised/automl.py#L53

Hi!
There is an issue with selecting Decision Tree model as the name contains a typo. 

Therefore, it should be corrected from "Decicion Tree" to "Decision Tree".

**Comment by pplonski** [comment]
Good catch @molspace, wanna do a PR?

**Comment by molspace** [comment]
Sure @pplonski , i would like to do a PR, thank you!

**Comment by pplonski** [comment]
Fixed with https://github.com/mljar/mljar-supervised/pull/664

Thank you @molspace!
