### ISSUE TITLE
Bug: 'KNeighborsAlgorithm' object has no attribute 'classes_'

### ISSUE THREAD

**Issue by strukevych** [mljar/mljar-supervised#669]
Current behavior:
'KNeighborsAlgorithm' object has no attribute 'classes_'
Problem during computing permutation importance. Skipping ...

Expected: KNeighbors to be trained

**Comment by pplonski** [comment]
Which version are you using?

**Comment by strukevych** [comment]
Python 3.11
mljar 1.1.1

**Comment by pplonski** [comment]
Thanks @strukevych, looks like it is some bug. PR are welcome!

**Comment by Hk669** [comment]
hey @pplonski ,  i am keen on contributing and would like to gather more information to better understand the problem and work towards a resolution.

**Comment by Hk669** [comment]
@pplonski , made a PR #679 . 
i think this will solve the issue for the _classes attribute in the KNieghborsAlgorithm

**Comment by pplonski** [comment]
Thank you @Hk669, I've added comments to PR.

**Comment by pplonski** [comment]
@Marchlak are we able to reproduce the issue, or it was fixed with 1.5 scikit-learn?

**Comment by Marchlak** [comment]
@pplonski I haven't encountered this problem
