### ISSUE TITLE
Question: Stacking is relevant?

### ISSUE THREAD

**Issue by strukevych** [mljar/mljar-supervised#674]
I found that stacking includes models which is learned almost randomly (KNN as an example) with 0.51-0.55 accuracy, while other models are much better

Do we have some checks to include models that improve at least something at stacking or we are adding that without checking for noise?

If we are not checking for noise, then we probably need to add such functionality and it will help us to bring better stacked models both by performance and prediction results

**Comment by pplonski** [comment]
We select top K performing models from each algorithm family for stacking. From my experience it is working fine.
