### ISSUE TITLE
Feature: turn off the preprocessing step 

### ISSUE THREAD

**Issue by cocoftn** [mljar/mljar-supervised#678]
The framework automatically add datetime features which i don't need"ds_Month", "ds_Day", "ds_WeekDay","ds_DayOfYear","ds_Days_Diff_To_Min".

it would be nice if we could have the possibility to skip all the preprocessing stage

**Comment by pplonski** [comment]
Please convert datetime features by yourself to numeric or just skip that feature. There is no way to switch off datetime preprocessing step. You can also fork the project and update the code.
