### ISSUE TITLE
ImportError: cannot import name 'interp' from 'scipy'

### ISSUE THREAD

**Issue by haim-cohen-moonactive** [mljar/mljar-supervised#691]
On January 20th, 2024 scypi released version 1.12.0 which broke its compatibility withthe old scikit-plot version 0.37, used by mljar-supervised. Since then, when importing AutoML (```from supervised.automl import AutoML```) you get the following error:
```
ImportError: cannot import name 'interp' from 'scipy' (/Users/someuser/temp/venv/lib/python3.9/site-packages/scipy/__init__.py)
```

It also happens on ```Python 3.11.7```.

WORKAROUND:
Add to requirements.txt ```scipy==1.11.4```, which installs the previous version of scipy.

@pplonski, long-term I guess replacing ```scikit-plot``` should take place, as it stopped developing on 2018. As a a quick fix for now, I would add the following to requirements.txt
```
scipy>=1.6.1,<=1.11.4
```
instead of ```scipy>=1.6.1```

Thanks!

**Comment by namelessperson0** [comment]
I am also facing the same error.
`ImportError: cannot import name 'interp' from 'scipy'`

**Comment by pplonski** [comment]
Thank you @haim-cohen-moonactive, I've added limit for `scipy` version. I will take a look at `scikit-plot` as well.

**Comment by cmontesv** [comment]
any clue when requirements.txt file doesn't exist?
thanks

**Comment by haim-cohen-moonactive** [comment]
> any clue when requirements.txt file doesn't exist? thanks

@cmontesv Just install scipy==1.11.4. If inside a notebook:
```%pip install scipy==1.11.4```

This will make mljar work again.

**Comment by cmontesv** [comment]
> > any clue when requirements.txt file doesn't exist? thanks
> 
> @cmontesv Just install scipy==1.11.4. If inside a notebook: `%pip install scipy==1.11.4`
> 
> This will make mljar work again.

it worked, thank you very much

**Comment by lzzzhh** [comment]
there is an error ImportError: cannot import name 'reshape' from 'scipy', my scipy version is 1.12.0,  python version is 3.9, what version of scipy is suitable for me
Thank!

**Comment by pplonski** [comment]
Please install scipy 1.11.4, I will fix it tomorrow and do new release.

**Comment by dvsuresh26** [comment]
Getting same [ImportError: cannot import name 'interp' from 'scipy'] error even after installing scipy-1.11.4

**Comment by pplonski** [comment]
Please update mljar-supervised to the latest version.

**Comment by rafael-ferreira-soares** [comment]
Try replacing the line "from scipy import interp" to "from numpy import interp" in the files "metrics.py" and "plotters" below:
conda/envs/scipy/lib/python3.10/site-packages/scikitplot/metrics.py
conda/envs/scipy/lib/python3.10/site-packages/scikitplot/plotters.py

The paths and names may be different in your installation.

It worked for me.

**Comment by jublicastino** [comment]
@pplonski @namelessperson0 @haim-cohen-moonactive 

**ImportError: cannot import name 'interp' from 'scipy'**
I downgrade to scipy 1.11.4 as was explained in the thread but  issue exists.
anaconda navigator is 2.6.2 previously 2.6.1. before update I didnot have issue.

 I  am not using  mljar-supervised.

may I ask you where can I find 
****requirements.txt** ? to change the text?**

additionally: i checked the scipy version in terminal it shows scipy 1.11.4 but in jupyter where i get the error its scipy 1.13.1

i have 2 other environments in anaconda than BASE. on all the scipy version in terminal is 1.11.4 but in jupter i get 1.13.1.
so I guess this is the issue for my case.

any one knows why is that?

**Comment by pplonski** [comment]
The issue is because scikit-plot depends on old version of scipy. To fix issue you can install mljar-scikit-plot it is fork maintained by me

**Comment by pplonski** [comment]
I created fork of scikit-plot with updated dependencies https://github.com/mljar/mljar-scikit-plot and mljar-supervised depends on our fork of scikit-plot.

**Comment by andearaujo92** [comment]
> I created fork of scikit-plot with updated dependencies https://github.com/mljar/mljar-scikit-plot and mljar-supervised depends on our fork of scikit-plot.

I can't import it as scikit-plot or scikitplot

**Comment by pplonski** [comment]
Hi @andearaujo92!

Have you installed the `mljar-scikit-plot`?

```
pip install mljar-scikit-plot
```

What environment are you using?

**Comment by andearaujo92** [comment]
> Hi @andearaujo92!
> 
> Have you installed the `mljar-scikit-plot`?
> 
> ```
> pip install mljar-scikit-plot
> ```
> 
> What environment are you using?

Yes I have installed it, but I could not import.
I am using an environment created using Venv

**Comment by pplonski** [comment]
What is output from `pip freeze`?
