### ISSUE TITLE
Select number of cross-validation folds

### ISSUE THREAD

**Issue by tmontana** [mljar/mljar-supervised#7]
Would be great to be able to set the number of cross-val folds.  On the MLJAR.com platform I always use 15.  Ideally we can set any number as long as number of folds <= number of rows.  thanks

**Comment by pplonski** [comment]
Sure, will try to fix this with issue #6. What is max  number of folds you would like to have in graphical interface?

**Comment by tmontana** [comment]
Ideally max number of folds = number of rows in training set such that we would get 'leave-one-out' cross-validation capabilities (useful for smaller datasets).

**Comment by pplonski** [comment]
I was thinking about this issue and I would like to keep `AutoML` constructor interface simple and without adding new variables. Please try following solution:

```python
automl = AutoML()
# set your validation settings
automl._validation = {"validation_type": "kfold", "k_folds": 100, "shuffle": False, "stratify": False}
automl.fit(X, y)
```
You need to set validation before calling `fit` method. Here are described [validation types](https://github.com/mljar/mljar-supervised/wiki/Validation). 

Please let me know if it works for you.

**Comment by tmontana** [comment]
Looks great.  I will start testing this week.  Thanks
