### ISSUE TITLE
problem run in colab

### ISSUE THREAD

**Issue by Mr-Khans** [mljar/mljar-supervised#706]
Error for 1_Baseline
cannot import name 'SequenceNotStr' from 'pandas._typing' (/usr/local/lib/python3.10/dist-packages/pandas/_typing.py) Traceback (most recent call last): File "/usr/local/lib/python3.10/dist-packages/supervised/base_automl.py", line 1195, in _fit trained = self.train_model(params) File "/usr/local/lib/python3.10/dist-packages/supervised/base_automl.py", line 404, in train_model self.keep_model(mf, model_subpath) File "/usr/local/lib/python3.10/dist-packages/supervised/base_automl.py", line 317, in keep_model self.select_and_save_best() File "/usr/local/lib/python3.10/dist-packages/supervised/base_automl.py", line 1381, in select_and_save_best ldb.to_csv(os.path.join(self._results_path, "leaderboard.csv"), index=False) File "/usr/local/lib/python3.10/dist-packages/pandas/util/_decorators.py", line 211, in wrapper raise TypeError(msg) File "/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py", line 3720, in to_csv styler = Styler(self, uuid="") File "/usr/local/lib/python3.10/dist-packages/pandas/util/_decorators.py", line 211, in wrapper raise TypeError(msg) File "/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py", line 1162, in to_csv File "/usr/local/lib/python3.10/dist-packages/pandas/io/formats/csvs.py", line 24, in from pandas._typing import SequenceNotStr ImportError: cannot import name 'SequenceNotStr' from 'pandas._typing' (/usr/local/lib/python3.10/dist-packages/pandas/_typing.py)

**Comment by pplonski** [comment]
Thanks @Mr-Khans for reporting, the error looks really strange. Any insights about your input dataset and code?

**Comment by Mr-Khans** [comment]
ThxSM for quick response), it turned out that the problem was downgrading the version of pandas == 2.0 and matplotlib==3.1.3 , for the colab version)
