### ISSUE TITLE
Creating a Simple enough UI that a person from Non-tech background could understand.

### ISSUE THREAD

**Issue by Akshat-Rastogi-6** [mljar/mljar-supervised#724]
Greetings, @pplonski
My name is Akshat, and I would like to suggest a new user interface design that is probably simpler for non-techies. These days, machine learning is a rapidly growing field that is utilized by individuals with backgrounds in business, marketing, and advertising in addition to ML engineers and data scientists. They can save a ton of time with a straightforward user interface. For the time being, streamlit is one option I have in mind, but the nice-gui Python library is equally good.

Please review my proposal and decide if it is worthwhile to try. If so, kindly let me to add to it.

Thank you,
Akshat Rastogi

**Comment by Akshat-Rastogi-6** [comment]
I appreciate your prompt reply; it is nice to hear that we are on the same track. I realized that data scientists and machine learning engineers would benefit from using the model as a web application. Although you can work with sizable datasets there, some students need machine learning (ML) in order to finish their research projects. For them, a web app might be too much. A code-free MLJAR website that processes the data and generates a final document containing your findings may be the answer to this issue.

Pardon me if I misunderstood any aspect of your work.

**Comment by pplonski** [comment]
You understand it correctly. We also work on Mercury framework for publishing notebooks as web apps, https://runmercury.com The MLJAR Studio is complete platfrom for buliding and publishing Python projects.
