### ISSUE TITLE
Binary Classification on Imbalanced Dataset

### ISSUE THREAD

**Issue by dsimop** [mljar/mljar-supervised#744]
**Context:**

* Binary classification dataset with 35 input features and 148,532 records.
* Dataset distribution: 139,917 `class0` and 8,615 `class1` records.
* Preprocessing steps applied (e.g. na_fill_median) to handle missing values in input features.
* The proposed model was a Stacked Ensemble one.

**Problem:**

The sum of the confusion matrix values is **12,922**, which is significantly lower than the total number of records (**148,532**). 
Is that normal/expected? Can it be clarified how mljar-supervised currently handles such a scenario?

**Comment by pplonski** [comment]
Hi @dsimop,

Thank you for reporting, could you please provide full code to reproduce the issue?

**Comment by dsimop** [comment]
Hi @pplonski, I will close this issue and reopen an updated one, since I created a perfectly balanced dataset but observed a similar situation.

Thank you.
