### ISSUE TITLE
Add SHAP explanations to models

### ISSUE THREAD

**Issue by pplonski** [mljar/mljar-supervised#75]
Please add
- SHAP summary plot
- SHAP dependence plots
- SHAP decision plots for top-10 best predictions and top-10 worst prediction (the later might be more important)

**Comment by pplonski** [comment]
Please be careful with shap values shape. Take a look at https://github.com/slundberg/shap/issues/526

**Comment by pplonski** [comment]
Add condition for less than 6 features.

**Comment by pplonski** [comment]
Done. Tests will be added with this issue https://github.com/mljar/mljar-supervised/issues/69

**Comment by Tonywhitemin** [comment]
Hi @pplonski,
It's me again (laugh), sorry for that but I am little confused now...
Image below is the result of "**SHAP feature important**".
I don't know how to explain why the trend of Learner1 is almost reversed with SHAP value?
Could you help? Thanks!
![image](https://user-images.githubusercontent.com/88414200/173030800-b490d8c4-4202-4b2c-ad69-2c89d9781965.png)

**Comment by pplonski** [comment]
Hi, I have no idea, maybe try to ask on SHAP github repo?

**Comment by Tonywhitemin** [comment]
Ok, thanks!👍

**Comment by StrangeNPC** [comment]
Hi @Tonywhitemin , did you ever find out why?
