### ISSUE TITLE
Question: Lineare Models

### ISSUE THREAD

**Issue by Crefok** [mljar/mljar-supervised#774]
Hey all,
I have a question about removing the lineare Models regarding to the amount of Rows in the Dataset. 
Why is there a limit of 10_000 Datapoints for removing the linear Model, in my opinion there shouldn't be a reason for that?

https://github.com/mljar/mljar-supervised/blob/master/supervised/base_automl.py#L827

Regards

**Comment by pplonski** [comment]
The linear model is very slow for data with more than 10,000 rows, that's why I'm disabling it.

I would love to add faster implementation of linear models, for example https://github.com/VowpalWabbit/vowpal_wabbit
