### ISSUE TITLE
classification, predict_all - conflicting labels vs probabilities 

### ISSUE THREAD

**Issue by tuomassiren** [mljar/mljar-supervised#778]
Have I misunderstood the predict_all or label meaning in classification prediction?
My assumption is that the "label" should be "away_team" when "prediction_away_team" is > 0.5 in my example?

```
prediction = model.predict_all(games)
prediction[(prediction["label"] == "away_team") & (prediction["prediction_away_team"] < 0.5)]
```

```
(index)	prediction_away_team	prediction_home_team	label
25	0.493569	0.506431	away_team
26	0.495583	0.504417	away_team
56	0.495583	0.504417	away_team
83	0.495583	0.504417	away_team
110	0.495583	0.504417	away_team
136	0.495583	0.504417	away_team
140	0.499876	0.500124	away_team
150	0.497172	0.502828	away_team
153	0.495583	0.504417	away_team
196	0.493468	0.506532	away_team
203	0.495583	0.504417	away_team

```

`prediction[(prediction["label"] == "away_team") & (prediction["prediction_away_team"] > 0.5)]`

```
(index)	prediction_away_team	prediction_home_team	label
0	0.563400	0.436600	away_team
4	0.563400	0.436600	away_team
6	0.533648	0.466352	away_team
7	0.568224	0.431776	away_team
8	0.614467	0.385533	away_team
...	...	...	...
215	0.600708	0.399292	away_team
216	0.510345	0.489655	away_team
219	0.614467	0.385533	away_team
224	0.563400	0.436600	away_team
225	0.507745	0.492255	away_team

```

**Comment by pplonski** [comment]
Hi @tuomassiren,

You have assumed that threshold is 0.5. You need to check in report files what is threshold for your model. Report files are markdown files in the `results_path` directory. Please let me know if you found it.

**Comment by tuomassiren** [comment]
Right. Maybe this? Ensemble/README.md

## Confusion matrix (at threshold=0.570203)
|                      |   Predicted as away_team |   Predicted as home_team |
|:---------------------|-------------------------:|-------------------------:|
| Labeled as away_team |                    12056 |                     5508 |
| Labeled as home_team |                     8881 |                    13031 |

A) What's the relation of this to the predict_all?
B) How should the dataframe returned by predict_all be interpreted?
Two examples from above:

```
(index)	prediction_away_team	prediction_home_team	label
25	0.493569	0.506431	away_team
```
Classified as "away_team", with 49.3569% probability? 
Not classified as "home_team" with 50.6431% probability?
```
(index)	prediction_away_team	prediction_home_team	label
0	0.563400	0.436600	away_team
```
Classified as "away_team", with 56.3400% probability?

**Comment by pplonski** [comment]
A)

Confusion matrix is computed based on validation data and it tells you how well model classify samples. It is using the threshold 0.57 for predicting class label.

B)
The 0.57 is your threshold that gives you the highest accuracy. You can try different threshold values. 

If prediction probability is below 0.57 then it is class 0 - in your case it is `away_team`.

You can search for different threshold values that will optimize your cost function.

Are you happy with model performance from MLJAR AutoML?

**Comment by tuomassiren** [comment]
Thank you for the good answer. 
The model performance is on par with other implementations, as far as I'm aware.
