### ISSUE TITLE
Add probability distribution of target and predicted classes for classification

### ISSUE THREAD

**Issue by pplonski** [mljar/mljar-supervised#82]

**Comment by shahules786** [comment]
hey @pplonski I can work on this issue.

**Comment by pplonski** [comment]
OK, it's yours.

**Comment by shahules786** [comment]
hey, which plot do do you like? histplot or kdeplot? @pplonski

**Comment by pplonski** [comment]
I prefer histplot.

**Comment by shahules786** [comment]
@pplonski  temporarily pausing working on this issue due to some implementation complexities.
