### ISSUE TITLE
Cant load CatBoost model for predictions

### ISSUE THREAD

**Issue by pplonski** [mljar/mljar-supervised#85]
In the regression task I got an error:

```python
Only one of parameters ['verbose', 'logging_level', 'verbose_eval', 'silent'] should be set
```

It is related to https://github.com/catboost/catboost/issues/696

**Comment by Anaststam** [comment]
I also tried again to build from scratch after the fix was announced but its still not working.

**Comment by pplonski** [comment]
fixed with new catboost version
