### ISSUE TITLE
Random forest very slow in spite of setting low model_time_limit

### ISSUE THREAD

**Issue by tmontana** [mljar/mljar-supervised#86]
Hi. With model_time_limit = 500, 1 random forest model takes 10,305 seconds (10 k-folds).  This setting works better for XGBoost where time_limit=1000 takes about 1,200 seconds and time_limit=500 takes the same time (must be absolute minimum).  Can anything be adjusted for RF algo?

Also I noticed that it's only using 10 cores at the very max.  Not the case with XGBoost where it's able to use all cores on the machine.  Is that an SK-learn limitation or a setting in this library?

Thanks,

**Comment by pplonski** [comment]
1. To make things faster, please set `explain_level=0` in `AutoML` constructor. Switching off explanations make fitting much faster.
2. RF should use all cores, it has `n_jobs=-1`
3. I assume you are running binary classification? I've noticed that sklearn tree based algorithms can be very slow on regression tasks with `criterio=mae` and it was switched off in `0.3.5` version of mljar-supervised.

**Comment by tmontana** [comment]
1. already the case.  explain_level =0

2. yes I see that in your code - yet it's only using 10 cores for some reason.  I tested it on a machine with 48 cores and one with 96 cores.  Stuck at using only 10.  I'll try running a plain vanilla RF from SKL to see if that's where problem is coming from.

3. yes binary classification.

**Comment by pplonski** [comment]
Hmm, one more thing, I've added a feature that RF (and other algorithms that learn in iterations) should do at least 5 steps (https://github.com/mljar/mljar-supervised/issues/68). Maybe that's the problem?

**Comment by pplonski** [comment]
An regarding not using all cores, what is your data shape?

**Comment by tmontana** [comment]
The learning_curves charts show a total of 50 trees are being built.

Shape of X is 1.3mm rows by 270 columns.  Machine memory used is 25 gigs / 125 total.

**Comment by pplonski** [comment]
It should use all cores. I was worried that maybe there are too few columns to use all cores. When I'm training RF I observed that it is using all cores but not at 100%, let's say 35-50%. When I train xgboost all cares are set to 100%. Maybe you have a similar situation?

The RF is adding 10 trees in each iteration, so 50 trees = 5 iterations (the minimum required I set), do you think that 5 steps it too much?

Have you tried lightgbm or catboost?

**Comment by tmontana** [comment]
Ok so that explains the 50 trees minimum.  Would be nice to have that as an advanced parameters as for my dataset for instance running 'Normal' with 9 models (10 k-folds) takes more than 48 hours - makes it tough to iterate.

I would have also expected that it would use all cores at less than 100% 
![ScreenClip](https://user-images.githubusercontent.com/18288458/81810907-13b1c480-9524-11ea-833e-df6f263c5912.png)
![ScreenClip](https://user-images.githubusercontent.com/18288458/81810919-1a403c00-9524-11ea-981b-04278b35c2ba.png)

but no.  See attached screenshot.

![image](https://user-images.githubusercontent.com/18288458/81810980-30e69300-9524-11ea-96df-52e90e002f12.png)

**Comment by tmontana** [comment]
XGBoost is fine.  Will try the other algos too but wanted to test performance using RF as well.

**Comment by pplonski** [comment]
Just checked the sklearn, please take a look at this: https://github.com/scikit-learn/scikit-learn/issues/4459

They propose to:
```python
import affinity
import multiprocessing
affinity.set_process_affinity_mask(0, 2**multiprocessing.cpu_count()-1)
```

**Comment by tmontana** [comment]
I figured out the non-use of all processors.  Because of the low model_time_limit none of the models being run had n_estimators > 10.  Since the paralellization is 1 core per estimator there is no way system was going to be using more than 10 cores.  Running sklearn directly with n_estimators>10 confirmed that.
